- Makefile
- README.md
- `make install` command
- `make key-generate` command
- `make shell` command
- Updated README to optimize the setup instructions
---
⚠️ This is branched from #3
> Makefile optimizations

- config/nova.php
- Simon de Bruijn to nova users config
> Add email Simon de Bruijn to nova users config

- .github/CODEOWNERS
- Added Bram and Simon as code owners
> Add Bram and Simon as code owners

- Makefile
- app/Domain/Subscriptions/Models/SubscriptionModel.php
- app/Domain/Subscriptions/Repositories/SubscriptionRepository.php
- database/seeders/SubscriptionsSeeder.php
- tests/Domain/Subscriptions/Repositories/SubscriptionRepositoryTest.php
- Added `make seed` command
- Extended `seed` command to `make install` command
- Extended `Subscription` seeder with a check for existing seeds
> Improve install script

- app/Insightly/Listeners/CreateContact.php
- app/Insightly/Resources/OpportunityResource.php
- app/Insightly/Serializers/LinkSerializer.php
- phpunit.xml
- tests/Insightly/Listeners/CreateContactTest.php
- Prevent uploading contributors to Insightly
- Extend LinkSerializer with contact type to set correct Insightly role
---
Ticket: https://jira.uitdatabank.be/browse/PPF-29
> PPF-29 Insightly contact tweaks

- .env.ci
- .env.example
- README.md
- app/Providers/AuthServiceProvider.php
- config/auth.php
- config/auth0.php
- Moved login parameters config to an ENV variable so it's easy to update later in appconfig by coworkers other than the developers
---
Ticket: https://jira.uitdatabank.be/browse/PPF-70
> PPF-70 Move login parameters to env

- app/Providers/AuthServiceProvider.php
- config/auth.php
- config/auth0.php
- Moved auth0 login parameters from `config/auth.php` to `config/auth0.php`
> Move auth0 login parameters to `auth0.php`

- app/Domain/Auth/CurrentUser.php
- app/Domain/Auth/Models/UserModel.php
- app/Domain/Auth/Repositories/UserRepository.php
- app/Domain/Integrations/Controllers/IntegrationController.php
- Added first name and last name to custom `UserModel` with information retrieved from the `userinfo` endpoint
---
Ticket: https://jira.uitdatabank.be/browse/PPF-29
> PPF-29 Improve user info

- app/Domain/Organizations/Events/OrganizationUpdated.php
- app/Domain/Organizations/Models/OrganizationModel.php
- app/Insightly/InsightlyServiceProvider.php
- app/Insightly/Listeners/UpdateOrganization.php
- app/Insightly/Resources/OrganizationResource.php
- app/Insightly/Serializers/OrganizationSerializer.php
- tests/Insightly/InsightlyClientTest.php
- tests/Insightly/Listeners/UpdateOrganizationTest.php
- Added new Eloquent Model event `OrganizationUpdated`
- Added new Insightly listener `UpdateOrganization`
- Extend `InsightlyClient` with `update` method for organization
---
Ticket: https://jira.uitdatabank.be/browse/PPF-92
> PPF-92 Update organization in insightly

- app/Domain/Organizations/Models/OrganizationModel.php
- app/Domain/Organizations/Organization.php
- app/Domain/Organizations/Repositories/EloquentOrganizationRepository.php
- app/Insightly/Listeners/UpdateOrganization.php
- app/Insightly/Resources/OpportunityResource.php
- app/Insightly/Serializers/CustomFields/IntegrationTypeSerializer.php
- app/Insightly/Serializers/CustomFields/InvoiceEmailSerializer.php
- app/Insightly/Serializers/CustomFields/VatSerializer.php
- app/Insightly/Serializers/OpportunitySerializer.php
- app/Insightly/Serializers/OrganizationSerializer.php
- app/Nova/Resources/Contact.php
- app/Nova/Resources/Organization.php
- database/migrations/2022_12_21_141436_add_invoice_email_to_organizations_table.php
- tests/Domain/Organizations/Repositories/EloquentOrganizationRepositoryTest.php
- tests/Insightly/InsightlyClientTest.php
- tests/Insightly/Listeners/CreateOrganizationTest.php
- tests/Insightly/Listeners/UpdateOrganizationTest.php
- Added invoice email to Organization
---
Ticket: https://jira.uitdatabank.be/browse/PPF-98
> PPF-98 Add invoice email to Organization

- app/Domain/Organizations/Events/OrganizationDeleted.php
- app/Domain/Organizations/Models/OrganizationModel.php
- app/Insightly/InsightlyServiceProvider.php
- app/Insightly/Listeners/CreateOrganization.php
- app/Insightly/Listeners/DeleteOrganization.php
- app/Insightly/Listeners/UpdateOrganization.php
- app/Insightly/Repositories/EloquentInsightlyMappingRepository.php
- app/Insightly/Repositories/InsightlyMappingRepository.php
- tests/Insightly/Listeners/DeleteOrganizationTest.php
- Made it possible to delete organization from Insightly
- Added method `deleteById` on `InsightlyMappingRepository`
---
Ticket: https://jira.uitdatabank.be/browse/PPF-93
> PPF-93 Delete organization from Insightly

- .github/dependabot.yml
- Added missing `interval` option
---
Ticket: https://jira.uitdatabank.be/browse/PPF-99
> PPF-99 Fix dependabot

- app/Insightly/InsightlyServiceProvider.php
- app/Insightly/Listeners/CreateContact.php
- app/Insightly/Listeners/CreateOpportunity.php
- app/Insightly/Listeners/CreateOrganization.php
- app/Insightly/Listeners/UpdateOrganization.php
- Fixed binding Insightly client interface with concrete implementation
> Fix binding Insightly client interface with concrete implementation

- app/Domain/Contacts/Events/ContactDeleted.php
- app/Domain/Contacts/Models/ContactModel.php
- app/Domain/Contacts/Repositories/ContactRepository.php
- app/Domain/Contacts/Repositories/EloquentContactRepository.php
- app/Insightly/InsightlyServiceProvider.php
- app/Insightly/Listeners/DeleteContact.php
- tests/Domain/Contacts/Repositories/EloquentContactRepositoryTest.php
- tests/Insightly/Listeners/DeleteContactTest.php
- tests/Insightly/Repositories/EloquentInsightlyMappingRepositoryTest.php
- `ContactDeleted` event and associated `DeleteContact` listener to delete deleted contacts in Inisghtly.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-89
> PPF-89 Delete contact

- app/Domain/Contacts/Policies/ContactPolicy.php
- app/Policies/ContactPolicy.php
- app/Providers/AuthServiceProvider.php
- Added a `ContactPolicy` so it's not possible to restore deleted contacts.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-109
> PPF-109 Do not restore contacts

- app/Domain/Coupons/Coupon.php
- app/Domain/Coupons/CouponStatus.php
- app/Domain/Coupons/Models/CouponModel.php
- app/Domain/Coupons/Repositories/EloquentCouponRepository.php
- database/migrations/2023_01_13_142805_update_coupons_table.php
- database/seeders/CouponsSeeder.php
- tests/Domain/Coupons/Repositories/EloquentCouponRepositoryTest.php
- Enum `CouponStatus`
- Added `isDistributed` to `Coupon`
---
Ticket: https://jira.uitdatabank.be/browse/PPF-120
> PPF-120 Coupon isDistributed

- app/Insightly/Exceptions/ContactCannotBeUnlinked.php
- app/Insightly/InsightlyServiceProvider.php
- app/Insightly/Listeners/DeleteContact.php
- app/Insightly/Listeners/UnlinkContact.php
- app/Insightly/Resources/InsightlyOpportunityResource.php
- app/Insightly/Resources/OpportunityResource.php
- tests/Insightly/Listeners/DeleteContactTest.php
- tests/Insightly/Listeners/UnlinkContactTest.php
- tests/Insightly/Resources/InsightlyOpportunityResourceTest.php
- `unlinkContact` on `OpportunityResource`.
- Inisghtly listener to delete a contact now unlinks a contact.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-117
> PPF-117 unlink contact in Inisghtly

- package-lock.json
- package.json
- resources/ts/Pages/Integrations/Create.tsx
- resources/ts/app.tsx
- Upgrade Inertia.js v1.0
Used this guide: https://inertiajs.com/upgrade-guide
> Upgrade Inertia.js v1.0

- app/Domain/Contacts/Models/ContactModel.php
- app/Domain/Integrations/Models/IntegrationModel.php
- app/Domain/Organizations/Models/OrganizationModel.php
- Fixed Insightly mapping relationship by replacing `BelongsTo` relation with `HasMany`. After removing the primary key from the mappings table the relation became a has many relation
> Fix Insightly mapping relation

- nova-components/InsightlyLink/src/InsightlyLink.php
- nova-components/InsightlyLink/src/InsightlyType.php
- Open the details view of an Insightly resource instead of the detail panel inside the list view
> Open detail page inside Insightly

- .env.ci
- .env.example
- README.md
- app/Auth0/Auth0ServiceProvider.php
- app/Exceptions/Handler.php
- app/Insightly/InsightlyServiceProvider.php
- app/UiTiDv1/UiTiDv1ServiceProvider.php
- config/app.php
- config/auth0.php
- config/insightly.php
- config/uitidv1.php
- Added flags to enable integrations
---
Ticket: https://jira.uitdatabank.be/browse/PPF-128
> PPF-128 Add flags to enable integrations

- app/Domain/Integrations/IntegrationStatus.php
- app/Nova/Resources/Integration.php
- Added missing states `PendingApprovalIntegration` and `PendingApprovalPayment`
- As preparation for the migration commands
> Add states `PendingApprovalIntegration` and `PendingApprovalPayment`

- app/Insightly/InsightlyServiceProvider.php
- app/Insightly/Listeners/CreateProjectWithCoupon.php
- tests/Insightly/Listeners/CreateProjectWithCouponTest.php
- Renamed `ActivateIntegrationWithCoupon` to `CreateProjectWithCoupon`
> Rename `ActivateIntegrationWithCoupon` to `CreateProjectWithCoupon`

- database/migrations/2023_01_03_115900_create_uitidv1_consumers_table.php
- Fixed unique constraints on `uitidv1_consumers` table (environment should be taken into account)
> Fix unique constraints on `uitidv1_consumers` table

- config/nova.php
> Add Jonas as Nova user

- app/Nova/Resources/Subscription.php
- Changed copy `Price` to `Subscription price (billed annually)` on Subscription
- Changed copy `Fee` to `Setup fee (billed once)` on Subscription
---
Ticket: https://jira.uitdatabank.be/browse/PPF-134
> PPF-134 Clarify copy price & fee

- app/Nova/Resources/Integration.php
- `Created` column on list & detail view of `Integration`
- Hide `Description` & `ID` from listview in `Integration`
- Add filters for `Created`, `Type`, `Subscription` & `Status`
- reorder fields on listview of Integration: from `Type`|`Name`|`Subscription`|`Status` to `Name`|`Type`|`Status`|`Subscription`
- Make all fields in `Integration` on listview sortable 
---
Ticket: https://jira.uitdatabank.be/browse/PPF-137
> PPF-137 refactor listview integrations

- app/Nova/Resources/Contact.php
- Hide `ID`, `First name` & `Last name` from listview for Resource `Contact`
- Reorder fields for Resource `Contact` from: `Type`|`e-mail`|`Integration` to `e-mail`|`Type`|`Integration`
- Make all fields for Resource `Contact` sortable in listView
- Add Filter for field `Type` on Resource `Contact`
---
Ticket: https://jira.uitdatabank.be/browse/PPF-138
> PPF-138 refactor contact resource

- app/Nova/Resources/Contact.php
- app/Nova/Resources/Integration.php
- app/Nova/Resources/Organization.php
- `Contact`, `Integration`, `Organization` are now findable by `ID` in the listview
---
Ticket: https://jira.uitdatabank.be/browse/PPF-143
> PPF-143 Make Resources findable by ID

- app/Nova/Resources/Subscription.php
- Made integration filterable on the subscriptions list
---
Ticket: https://jira.uitdatabank.be/browse/PPF-146
> PPF-146 Make integration filterable on subscriptions list

- app/Nova/Resources/Contact.php
- Sorted on integration name inside the contacts list
---
Ticket: https://jira.uitdatabank.be/browse/PPF-144
> PPF-144 Improve sorting relations

- app/Domain/Integrations/Events/IntegrationBlocked.php
- app/Domain/Integrations/Models/IntegrationModel.php
- app/Nova/Actions/BlockIntegration.php
- app/Nova/Resources/Integration.php
- tests/Domain/Integrations/Models/IntegrationModelTest.php
- Added action `BlockIntegration`
- Dispatch event `IntegrationBlocked`
- Follow-up pull requests will focus on Isnightly, Auth0 and UiTiD
---
Ticket: https://jira.uitdatabank.be/browse/PPF-149
> PPF-149 Add Laravel Nova Action BlockIntegration

- app/Insightly/InsightlyServiceProvider.php
- app/Insightly/Listeners/BlockOpportunity.php
- app/Insightly/Listeners/BlockProject.php
- tests/Insightly/Listeners/BlockOpportunityTest.php
- tests/Insightly/Listeners/BlockProjectTest.php
- Added `BlockOpportunity` Insightly listener
- Added `BlockProject` Insightly listener
---
Ticket: https://jira.uitdatabank.be/browse/PPF-149
> PPF-149 Block Project/Opportunity inside Insightly

- app/UiTiDv1/Listeners/BlockConsumers.php
- app/UiTiDv1/UiTiDv1ClusterSDK.php
- app/UiTiDv1/UiTiDv1EnvironmentSDK.php
- app/UiTiDv1/UiTiDv1ServiceProvider.php
- tests/UiTiDv1/Listeners/BlockConsumersTest.php
- Added `BlockConsumers` listener inside UiTiD domain which listens to the `IntegrationBlocked` event
---
Ticket: https://jira.uitdatabank.be/browse/PPF-149
> PPF-149 Block UiTiD consumers

- app/Auth0/Auth0ClusterSDK.php
- app/Auth0/Auth0ServiceProvider.php
- app/Auth0/Auth0TenantSDK.php
- app/Auth0/Listeners/BlockClients.php
- tests/Auth0/Listeners/BlockClientsTest.php
- Added `BlockClient` listener that will block Auth0 clients by removing grant types from the client
---
Ticket: https://jira.uitdatabank.be/browse/PPF-149
> PPF-149 Block Auth0 clients

- app/Domain/Integrations/Models/IntegrationModel.php
- app/Nova/Resources/Integration.php
- Displayed both Opportunity and Project links to Insightly
---
Ticket: https://jira.uitdatabank.be/browse/PPF-156
> PPF-156 Display both Opportunity and Project links

- app/Nova/Resources/Integration.php
- Hide the Organization field when creating or updating an Integration
---
Ticket: https://jira.uitdatabank.be/browse/PPF-157
> PPF-157 Hide Organization field

- app/Nova/Resources/Coupon.php
- app/Nova/Resources/Subscription.php
- Search subscription on id and description
- Search coupons on id
---
Ticket: https://jira.uitdatabank.be/browse/PPF-143
> PPF-143 Improve searchability

- app/Auth0/Auth0TenantSDK.php
- app/Auth0/Auth0Unauthorized.php
- Execute retry after 401 response
---
Ticket: https://jira.uitdatabank.be/browse/PPF-150
> PPF-150 request new token

- app/Domain/Integrations/Models/IntegrationModel.php
- app/Nova/Resources/Integration.php
- Removed status field from Integration form and gave it a default value of `Draft`
---
Ticket: https://jira.uitdatabank.be/browse/PPF-160
> PPF-160 remove status from integration form

- config/nova.php
> Add Bert as Nova admin user

- app/Domain/Integrations/Events/IntegrationUpdated.php
- app/Domain/Integrations/Models/IntegrationModel.php
- app/Insightly/InsightlyServiceProvider.php
- app/Insightly/Listeners/UpdateOpportunity.php
- app/Insightly/Listeners/UpdateProject.php
- app/Insightly/Resources/InsightlyOpportunityResource.php
- app/Insightly/Resources/InsightlyProjectResource.php
- app/Insightly/Resources/OpportunityResource.php
- app/Insightly/Resources/ProjectResource.php
- app/Insightly/Serializers/OpportunitySerializer.php
- app/Insightly/Serializers/ProjectSerializer.php
- phpunit.xml
- tests/Insightly/HttpInsightlyClientTest.php
- tests/Insightly/Listeners/UpdateOpportunityTest.php
- tests/Insightly/Listeners/UpdateProjectTest.php
- Added event `IntegrationUpdated`
- Added listeners `UpdateOpportunity` and `UpdateProject`
- Renamed `InsightlyClientTest` to `HttpInsightlyClientTest`
---
Ticket: https://jira.uitdatabank.be/browse/PPF-161
> PPF-161 update integration on insightly

- composer.json
- composer.lock
- tests/AssertRequest.php
- Fixed composer lock file for PHP 8.2
> Fix composer lock file for PHP 8.2

- app/Console/Commands/Migrations/MigrateProjects.php
- app/Domain/Integrations/Controllers/IntegrationController.php
- app/Domain/Integrations/Integration.php
- app/Domain/Integrations/Models/IntegrationModel.php
- app/Domain/Integrations/Repositories/EloquentIntegrationRepository.php
- app/Nova/Resources/Contact.php
- app/Nova/Resources/Integration.php
- tests/Auth0/Listeners/CreateClientsTest.php
- tests/Auth0/Listeners/UpdateClientsTest.php
- tests/Domain/Integrations/Repositories/EloquentIntegrationRepositoryTest.php
- tests/Insightly/HttpInsightlyClientTest.php
- tests/Insightly/Listeners/CreateOpportunityTest.php
- tests/Insightly/Listeners/CreateProjectWithCouponTest.php
- tests/Insightly/Listeners/CreateProjectWithOrganizationTest.php
- tests/Insightly/Listeners/UpdateOpportunityTest.php
- tests/Insightly/Listeners/UpdateProjectTest.php
- tests/Insightly/Resources/InsightlyOpportunityResourceTest.php
- tests/Insightly/Resources/InsightlyProjectResourceTest.php
- tests/UiTiDv1/Listeners/CreateConsumersTest.php
- tests/UiTiDv1/Listeners/UpdateConsumersTest.php
- Refactored contacts on integrations to be optional (this will make it consistent with the new URLs which will also be linked resources)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-153
> PPF-153 Refactor contacts on integration to be optional

- app/Auth0/Auth0ServiceProvider.php
- app/Auth0/Auth0TenantSDK.php
- app/Auth0/Listeners/BlockClients.php
- app/Auth0/Listeners/CreateClients.php
- app/Auth0/Listeners/UpdateClients.php
- app/Domain/Integrations/Controllers/IntegrationController.php
- app/Domain/Integrations/Events/IntegrationBlocked.php
- app/Domain/Integrations/Events/IntegrationCreated.php
- app/Domain/Integrations/Events/IntegrationUpdated.php
- app/Domain/Integrations/Events/IntegrationUrlCreated.php
- app/Domain/Integrations/Events/IntegrationUrlDeleted.php
- app/Domain/Integrations/Events/IntegrationUrlUpdated.php
- app/Domain/Integrations/Integration.php
- app/Domain/Integrations/IntegrationUrl.php
- app/Domain/Integrations/Models/IntegrationModel.php
- app/Domain/Integrations/Models/IntegrationUrlModel.php
- app/Insightly/Listeners/BlockOpportunity.php
- app/Insightly/Listeners/BlockProject.php
- app/Insightly/Listeners/CreateOpportunity.php
- app/Insightly/Listeners/UpdateOpportunity.php
- app/Insightly/Listeners/UpdateProject.php
- app/UiTiDv1/Listeners/BlockConsumers.php
- app/UiTiDv1/Listeners/CreateConsumers.php
- app/UiTiDv1/Listeners/UpdateConsumers.php
- tests/Auth0/Listeners/UpdateClientsTest.php
- tests/Domain/Integrations/Repositories/EloquentIntegrationRepositoryTest.php
- Added code to upload URLs to Auth0
- Follow-up ticket is created to remove login URL, see https://jira.uitdatabank.be/browse/PPF-180
---
Ticket: https://jira.uitdatabank.be/browse/PPF-153
> PPF-153 Upload URLs to Auth0

- app/Domain/Integrations/Models/IntegrationModel.php
- app/Nova/Resources/Contact.php
- app/Nova/Resources/Integration.php
- Remove the `hasOne` relationship for functional and technical contacts which conflicted with the `hasMany` relationship for contributors
---
Ticket: https://jira.uitdatabank.be/browse/PPF-185
> PPF-185 Fix contact creation

- app/Nova/Resources/IntegrationUrl.php
- Validate that only one login URL exists per environment, but also make sure that an update of the URL itself is still working
---
Ticket: https://jira.uitdatabank.be/browse/PPF-153
> PPF-153 Validate that only one login URL exists per environment

- package-lock.json
- package.json
- Update frontend dependencies (see commits)
> Update frontend dependencies

- .github/CODEOWNERS
- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Shared/Header.tsx
- resources/ts/Shared/Heading.tsx
- resources/ts/Shared/Layout.tsx
- resources/ts/i18n/initializeI18n.ts
- tailwind.config.js
- Header component
- colors in tailwind
- translations nl
---
Ticket: https://jira.uitdatabank.be/browse/PPF-167
> PPF-167 - navigation bar

- app/Router/TranslatedRoute.php
- package-lock.json
- package.json
- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/i18n/initializeI18n.ts
- routes/web.php
- [Use language detector to watch path language](https://github.com/cultuurnet/publiq-platform/commit/e42c5fa0667070ff2405dd6c5e96e9d456db4d30)
- [Get language from uri instead of key](https://github.com/cultuurnet/publiq-platform/commit/269268dfdaf63a08f5872dc2f37f35ebbf28b49e)
- [Change paths to include prefix](https://github.com/cultuurnet/publiq-platform/commit/035c8e21454b444d0cafccd75a587fee5d9ffb96)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-167
> PPF-167 - Infer language on frontend

- resources/ts/Shared/Card.tsx
- resources/ts/Shared/IntegrationTypeCard.tsx
- resources/ts/Shared/LinkButton.tsx
- resources/ts/Shared/SecondaryButton.tsx
- min height to IntegrationTypeCard
- LinkButton
---
Ticket: https://jira.uitdatabank.be/browse/PPF-164
> PPF-164-home-page

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Pages/Support/Index.tsx
- resources/ts/Shared/LinkButton.tsx
- resources/ts/Shared/SupportCard.tsx
- resources/ts/Shared/SupportTypes.tsx
- routes/web.php
-support page
-SupportTypes
-SupportCard
Desktop:
Mobile:
---
> PPF-188-support-page

- app/Http/Kernel.php
- app/Http/Middleware/SetLocale.php
- lang/en/validation.php
- lang/nl/validation.php
- resources/ts/Pages/Integrations/Create.tsx
- [Add middleware to set app locale](https://github.com/cultuurnet/publiq-platform/commit/a9536b6e896d34d9ac49e8d71c5ed70100435ed1)
- [Add validations nl](https://github.com/cultuurnet/publiq-platform/commit/3a2e8b902bdb3ea6516ffdd376f4293a1acfd1ae)
- [Add friendlier attribute names for validation messages](https://github.com/cultuurnet/publiq-platform/commit/c7c3a71a8f24869b85e53b906eed03140deb6be9)
> Translate validation messages

- resources/ts/Shared/Layout.tsx
- resources/ts/Shared/Page.tsx
- [Add Page component](https://github.com/cultuurnet/publiq-platform/commit/171e2bef63aad60afa55743f6e0aed52112b76a7)
- [Change Layout styling](https://github.com/cultuurnet/publiq-platform/commit/02ba8a8e13d0451fcc9357e14d3e4e608188bc86)
> Add page component

- app/Domain/Integrations/Controllers/IntegrationController.php
- app/Domain/Integrations/Controllers/StoreIntegration.php
- lang/nl/validation.php
- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Pages/Integrations/New.tsx
- resources/ts/Shared/Button.tsx
- resources/ts/Shared/ButtonLinkSecondary.tsx
- resources/ts/Shared/ButtonSecondary.tsx
- resources/ts/Shared/Card.tsx
- resources/ts/Shared/FormElement.tsx
- resources/ts/Shared/Input.tsx
- resources/ts/Shared/Page.tsx
-Button
-Integration form
-Card
-FormElement
Desktop:
Mobile:
---
> PPF-190-integration form

- app/Router/TranslatedRoute.php
> Hotfix translated route

- resources/translations/en.json
- resources/ts/Pages/Integrations/New.tsx
- resources/ts/Shared/Navigation.tsx
- resources/ts/hooks/useTranslateRoute.ts
> Fix translated paths

- .github/workflows/ci.yml
- resources/ts/Components/Integrations/Detail/ContactInfo.tsx
- [Set node version to 18.14](https://github.com/cultuurnet/publiq-platform/commit/3f90af6ece01042eaa2a123b5e56a822ce004d96)
- Fix contact info format issue prettier couldn't fix itself
> Update node version to 18.14

- app/Http/Middleware/TrustProxies.php
> Fix assets over HTTP by trusting all proxies.

- config/horizon.php
- config/nova.php
> Add Paul as developer

- app/Auth0/Auth0Client.php
- app/Auth0/Auth0TenantSDK.php
- app/Auth0/Events/ClientBlocked.php
- app/Auth0/Models/Auth0ClientModel.php
- app/Auth0/Policies/Auth0ClientPolicy.php
- app/Auth0/Repositories/EloquentAuth0ClientRepository.php
- app/Domain/Integrations/Integration.php
- app/Domain/Integrations/Models/IntegrationModel.php
- app/Nova/Resources/Auth0Client.php
- app/Nova/Resources/Integration.php
- app/Providers/AuthServiceProvider.php
- database/migrations/2022_12_08_152100_create_auth0_clients_table.php
- tests/Auth0/Listeners/BlockClientsTest.php
- tests/Auth0/Listeners/CreateClientsTest.php
- tests/Auth0/Listeners/UpdateClientsTest.php
- tests/Auth0/Repositories/EloquentAuth0ClientRepositoryTest.php
Added auth0 resource block on integration page
Old resource pools for auth0 and UidIdv1 consumers block on integration page.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-186
> PPF-186 auth0

- app/Console/Commands/Migrations/MigrateProjects.php
- app/Domain/Integrations/Integration.php
- app/Domain/Integrations/Models/IntegrationModel.php
- app/Nova/Resources/Integration.php
- app/Nova/Resources/UiTiDv1.php
- app/Providers/AuthServiceProvider.php
- app/UiTiDv1/Models/UiTiDv1ConsumerModel.php
- app/UiTiDv1/Policies/UiTiDv1ConsumerPolicy.php
- app/UiTiDv1/Repositories/EloquentUiTiDv1ConsumerRepository.php
- app/UiTiDv1/UiTiDv1Consumer.php
- app/UiTiDv1/UiTiDv1EnvironmentSDK.php
- database/migrations/2023_01_03_115900_create_uitidv1_consumers_table.php
- tests/UiTiDv1/Listeners/BlockConsumersTest.php
- tests/UiTiDv1/Listeners/CreateConsumersTest.php
- tests/UiTiDv1/Listeners/UpdateConsumersTest.php
- tests/UiTiDv1/Repositories/EloquentUiTiDv1ConsumerRepositoryTest.php
Added UiTiDv1 resource block on integration page
Old resource pools for UiTiDv1 consumers block on integration page.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-186
> PPF-186 UiTiDv1 consumer update

- .github/CODEOWNERS
- config/nova.php
Added myself (koen) to nova admin users and code owners
Removed Bert als admin user
> Added myself (koen) to nova admin users and code owners

- composer.json
- composer.lock
- Removed `/nova-components/ClientCredentials` local repo
> Removed `/nova-components/ClientCredentials` local repo

- app/Domain/Integrations/Integration.php
- Fix broken integration create
---
Ticket: https://jira.uitdatabank.be/browse/PPF-186
> PPF-186 Fix broken integration create

- app/Nova/Resources/Auth0Client.php
- app/Nova/Resources/UiTiDv1.php
open links in new tab
---
Ticket: https://jira.uitdatabank.be/browse/PPF-186
> PPF-186 open links in new tab

- app/Domain/Auth/Controllers/Callback.php
- app/Http/Kernel.php
- app/Http/Middleware/EncryptCookies.php
- app/Http/Middleware/SetAuthIdTokenCookie.php
On the request of @simon-debruijn I exposed the client id of a auth0 user to the frontend with a cookie.
Ticket: https://jira.uitdatabank.be/browse/UID-875
> UID-875 Added a cookie that exposes client id when logged in with auth0

- app/Nova/Actions/Auth0/ActivateAuth0Client.php
- app/Nova/Actions/Auth0/BlockAuth0Client.php
- app/Nova/Resources/Auth0Client.php
- Changed dispatch to dispatchNow so status field directly changes when activating/blocking key.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-197
> PPF-197 Added dispatchNow() for status field

- app/Nova/Actions/UiTiDv1/ActivateUiTiDv1Consumer.php
- app/Nova/Actions/UiTiDv1/BlockUiTiDv1Consumer.php
- app/Nova/Resources/UiTiDv1.php
- app/UiTiDv1/CachedUiTiDv1Status.php
- app/UiTiDv1/UiTiDv1ServiceProvider.php
- tests/UiTiDv1/CachedUiTiDv1StatusTest.php
Showing status field for UiTiD v1 integrations.
Bonus: showing status in colors, let me know if this is nice then I also add it for auth0
---
Ticket: https://jira.uitdatabank.be/browse/PPF-197
> Show status of UiTiD v1 by integrations

- app/Nova/Resources/Auth0Client.php
Show auth0 status in red/green to make it consistent with uitidv1 status
> Show auth0 status in red/green to make it consistent with uitidv1 status

- resources/ts/Components/ButtonLink.tsx
- resources/ts/Components/Footer.tsx
- resources/ts/Components/IntegrationTypeCard.tsx
- resources/ts/Components/Navigation.tsx
- resources/ts/Components/logos/VlaanderenLogo.tsx
- tailwind.config.js
-hover effect on navigation links
-transition to integration type cards
-font family
-background color
-footer height
-VlaanderenLogo size
---
Ticket: https://jira.uitdatabank.be/browse/PPF-199
> PPF-199-improve styling

- resources/ts/Components/UitIdWidget.tsx
For testing on acc environment
> Add console.log

- package-lock.json
- package.json
> Update vite dependencies

- config/nova.php
New admins:
* Wannes
* Corneel 
* Emma
> Add new admins

- resources/translations/nl.json
- resources/ts/Components/SupportTypes.tsx
- Roadmap
- Release notes
---
Ticket: https://jira.uitdatabank.be/browse/PPF-216
> PPF-216-support blocks

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/IntegrationCard.tsx
- resources/ts/Components/Link.tsx
- resources/ts/Pages/Integrations/Index.tsx
- Entry-api documentation link
- Product documentation links
- a tag for external links
---
Ticket: https://jira.uitdatabank.be/browse/PPF-220
> PPF-220-documentation links

- resources/ts/Components/UitIdWidget.tsx
- Change min height widget
---
Ticket: https://jira.uitdatabank.be/browse/UID-935
> UID-935 - Change min height widget

- app/Domain/Integrations/FormRequests/StoreIntegrationRequest.php
- lang/nl/validation.php
- resources/translations/nl.json
- resources/ts/Components/FormElement.tsx
- resources/ts/Pages/Integrations/New.tsx
- tests/Domain/Integrations/Mappers/StoreIntegrationMapperTest.php
-Privacy checkbox
---
Ticket: https://jira.uitdatabank.be/browse/PPF-227
> PPF-227-Add privacy checkbox

- config/horizon.php
- Added queue config for new environments
> Add queue config for new environments

- resources/translations/en.json
- resources/translations/nl.json
- Support page links
---
Ticket: https://jira.uitdatabank.be/browse/PPF-188
> PPF-188-Add support links

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/IntegrationCard.tsx
- Entry-api, search-api, widgets docs links
---
Ticket: https://jira.uitdatabank.be/browse/PPF-220
> PPF-220-Fix broken links

- app/Domain/Integrations/FormRequests/StoreIntegrationRequest.php
- Fixed typo in `StoreIntegrationRequest` causing crash
> Fixed typo in StoreIntegrationRequest causing crash

- resources/views/layouts/gtm.blade.php
- Checked for existence of part
> Check for existence of part

- config/horizon.php
> Add Jonas to horizon

- config/horizon.php
- config/nova.php
- Switched Luc from private email to work email
> Switch Luc from private email to work email

- app/Domain/Auth/Controllers/Access.php
- app/Domain/Auth/Controllers/AccessController.php
- app/Domain/Auth/Controllers/CallbackController.php
- app/Domain/Auth/Controllers/LoginController.php
- app/Domain/Auth/Controllers/LogoutController.php
- app/Domain/Auth/Controllers/TokenController.php
- app/Domain/Integrations/Integration.php
- app/Providers/AuthServiceProvider.php
- routes/api.php
- routes/web.php
- Added an endpoint to check if a user has access to an integration
---
Ticket: https://jira.uitdatabank.be/browse/PPF-236
> Add an endpoint to check if a user has access to an integration

- app/Domain/Auth/AuthServiceProvider.php
- app/Domain/Auth/Controllers/AccessController.php
- tests/Domain/Auth/Controllers/AccessControllerTest.php
- Take into account admin access 
---
Ticket: https://jira.uitdatabank.be/browse/PPF-240
> PPF-240 Take into account admin access

- app/Domain/Auth/AuthServiceProvider.php
- config/app.php
- tests/Domain/Auth/Controllers/AccessControllerTest.php
- Fixed dependency injection 
---
Ticket: https://jira.uitdatabank.be/browse/PPF-240
> PPF-240 Fix dependency injection

- app/Console/Commands/Migrations/MigrateProjects.php
- app/Console/Commands/Migrations/MigrationProject.php
- Import subscriptions based on plan and integration type
---
Ticket: https://jira.uitdatabank.be/browse/PPF-177
> PPF-177 Import subscription

- app/Domain/Integrations/Controllers/IntegrationController.php
- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/IntegrationCard.tsx
- routes/web.php
- Added a button to open a widget as an integrator
Note:
- This is a proof of concept and still needs fine-tuning for test/production widgets
---
Ticket: https://jira.uitdatabank.be/browse/PPF-250
> PPF-250 open widget as integrator

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/SupportCard.tsx
- Slack channel link button 
---
Ticket: https://jira.uitdatabank.be/browse/PPF-209
> PPF-209-Improve support slack

- resources/ts/Components/IntegrationCard.tsx
- Used normal link to open widget
---
Ticket: https://jira.uitdatabank.be/browse/PPF-250
> PPF-250 Use normal link to open widget

- resources/views/layouts/default.blade.php
- Add nofollow rule for search engines outside of production
---
Ticket: https://jira.publiq.be/browse/PPF-254
> Add nofollow rule for search engines outside of production

- resources/ts/Pages/Integrations/Index.tsx
- Do not lose focus when searching for integrations
---
Ticket: https://jira.publiq.be/browse/PPF-252
> Do not lose focus when searching for integrations

- resources/ts/Components/UitIdWidget.tsx
- UiTiD widget config: add test actions with seperator for Hans
---
Ticket: https://jira.uitdatabank.be/browse/UID-956
> UID-956 - Test actions with seperator for Hans

- resources/ts/layouts/Layout.tsx
-  [Fix typo](https://github.com/cultuurnet/publiq-platform/commit/ce8517197f787df9302db850914edcf2de765551)
---
Ticket: https://jira.uitdatabank.be/browse/UID-956
> UID-956 - Fix typo

- resources/ts/Components/UitIdWidget.tsx
- resources/ts/layouts/Layout.tsx
- use var for widgetUrl
---
Ticket: https://jira.uitdatabank.be/browse/UID-956
> UID-956 - use var for widgetUrl

- resources/ts/Pages/Integrations/New.tsx
- Terms of use and privacy statement links
---
Ticket: https://jira.uitdatabank.be/browse/PPF-227
> PPF-227-Fix links

- .eslintrc.json
- resources/ts/Components/UitIdWidget.tsx
- [Add missing widgetUrl](https://github.com/cultuurnet/publiq-platform/commit/2cc65d22acfbf56e7ce6981c88a18510cb67fb8a)
- [Make missing effect/memo dependency give error](https://github.com/cultuurnet/publiq-platform/commit/747ded1c68872d5c03459899e82eb475a38cc18b)
> Fix eslint warning

- app/Insightly/Resources/InsightlyOrganizationResource.php
- tests/Insightly/Resources/InsightlyOrganizationResourceTest.php
- Fixed typo with the Insightly key
> Fix typo with the Insightly key

- .github/workflows/dependabot-automerge.yml
- Approve dependabot pull requests to make auto merge work
> Approve dependabot pull requests to make auto merge work

- .github/CODEOWNERS
- Add Anahkiasen to codeowners
> Add Anahkiasen to codeowners

- resources/ts/Components/ContactsTable.tsx
- resources/ts/Components/HeroImage.tsx
- resources/ts/Components/IntegrationCard.tsx
- resources/ts/Components/Integrations/Detail/DeleteIntegration.tsx
- resources/ts/Components/StatusLight.tsx
- resources/ts/Components/SupportCard.tsx
- resources/ts/Components/SupportTypes.tsx
- resources/ts/Pages/Integrations/Index.tsx
- resources/ts/layouts/HomePageLayout.tsx
- tailwind.config.js
- Global styling changes
---
Ticket: https://jira.publiq.be/browse/PPF-275
> Global styling changes

- resources/ts/Components/IntegrationCard.tsx
- resources/ts/Components/IntegrationTypeCard.tsx
- resources/ts/Components/IntegrationTypes.tsx
- resources/ts/Pages/Integrations/Detail.tsx
- resources/ts/Pages/Integrations/New.tsx
- resources/ts/types/IntegrationType.ts
- only show price plan if it exists for current integration type
- Change type in url when type in form changes
- Rename usage of integrationTypeInfo
> Fix pricing errors

- database/seeders/SubscriptionsSeeder.php
- tariffs of the subscription plans
---
Ticket: https://jira.publiq.be/browse/PPF-287
> Correct subscription plans

- database/seeders/SubscriptionsSeeder.php
Incorrect integration type for a subscription plan 
---
Ticket: https://jira.uitdatabank.be/browse/PPF-287
> Fix incorrect integration type

- resources/ts/Components/UitIdWidget.tsx
- [Add correct integrations link for each language](https://github.com/cultuurnet/publiq-platform/commit/b9d6a7b0f3b1c2a2a6a4046ba5f8d410c79bf591)
- [Change integrations copy widget](https://github.com/cultuurnet/publiq-platform/commit/80d26049d477d8485c403aafab95f63f60fec389)
- [Remove Subscriptions](https://github.com/cultuurnet/publiq-platform/commit/dba02808f96c78c59c4b61bd29c6a5471355304e)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-273
> PPF-273 - Change links uitid widget

- resources/translations/en.json
* `EN` translations
---
Ticket: https://jira.uitdatabank.be/browse/PPF-274
> Add EN translations

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/Alert.tsx
- resources/ts/Components/Integrations/Detail/BillingInfo.tsx
- tailwind.config.js
- Added "free until live" warning to Billing page of integrations
---
Ticket: https://jira.publiq.be/browse/PPF-283
> Added "free until live" warning to Billing page of integrations

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Pages/Integrations/New.tsx
- Fixed unlocalized pricing plans descriptions/pricings
---
Ticket: https://jira.publiq.be/browse/PPF-288
> Fixed unlocalized pricing plans descriptions/pricings

- resources/views/layouts/default.blade.php
- Made title formatting consistent with other Publiq apps
---
Ticket: https://jira.publiq.be/browse/PPF-289
> Made title formatting consistent with other Publiq apps

- resources/ts/Pages/Integrations/Detail.tsx
- Fixed unlocalized integration types in detail page
---
Ticket: https://jira.publiq.be/browse/PPF-292
> Fixed unlocalized integration types in detail page

- resources/ts/Components/Dialog.tsx
- Fixed modals being rendered within parent element instead of the body
---
Ticket: https://jira.publiq.be/browse/PPF-296
> Fixed modals being rendered within parent element instead of the body

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/Integrations/Detail/ContactInfo.tsx
- Contacts description 
---
Ticket: https://jira.uitdatabank.be/browse/302
> PPF-302-Add contacts description

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/Integrations/Detail/IntegrationSettings.tsx
- resources/ts/Pages/Integrations/Detail.tsx
-Confirm leave dialog
---
Ticket: https://jira.uitdatabank.be/browse/PPF-286
> PPF-286-Add confirm leave dialog

- resources/ts/Components/Dialog.tsx
- Dialog content font size
---
Ticket: https://jira.uitdatabank.be/browse/PPF-304
> PPF-304-Change dialog font size

- resources/ts/Components/IntegrationTypeCard.tsx
- resources/ts/Components/RadioButtonGroup.tsx
- resources/ts/Components/SupportCard.tsx
-Support card
-Integration type card
-Radio button group
---
Ticket: https://jira.uitdatabank.be/browse/PPF-305
> PPF-305-Improve style

- app/Console/Commands/Migrations/MigrateContacts.php
- app/Console/Commands/Migrations/MigrationContact.php
- app/Console/Commands/Migrations/MigrationProject.php
- app/Console/Commands/Migrations/ReadCsvFile.php
- Added CLI command to migrate extra contacts from Insightly
---
Ticket: https://jira.uitdatabank.be/browse/PPF-282
> PPF-282 Add CLI command to migrate extra contacts from Insightly

- resources/ts/Components/Dialog.tsx
- Dialog font weight
---
Ticket: https://jira.uitdatabank.be/browse/PPF-303
> PPF-303-Change dialog font weight

- resources/ts/Components/Integrations/Detail/IntegrationSettings.tsx
- resources/ts/Pages/Integrations/Detail.tsx
- Save changes
- Cancel leave tab
---
Ticket: https://jira.uitdatabank.be/browse/PPF-286
> PPF-286-Fix confirm leave dialog

- app/Domain/Integrations/Repositories/EloquentIntegrationRepository.php
- resources/ts/Components/Pagination.tsx
- 10 results per page instead of 15
- Border radius
---
Ticket: https://jira.uitdatabank.be/browse/PPF-313
> PPF-313-Optimize pagination

- resources/ts/Components/ActivationFlow.tsx
- resources/ts/Components/ActivationRequest.tsx
- resources/ts/Components/IntegrationCard.tsx
- resources/ts/Pages/Integrations/Index.tsx
- Hide credentials for widgets
---
Ticket: 
https://jira.uitdatabank.be/browse/PPF-269
https://jira.uitdatabank.be/browse/PPF-295
> PPF-269-Hide credentials for widgets

- resources/ts/Components/ButtonLink.tsx
- resources/ts/Components/ButtonLinkSecondary.tsx
- resources/ts/Components/ButtonPrimary.tsx
- resources/ts/Components/ButtonSecondary.tsx
- ButtonLink
- ButtonLinkSecondary
- Button Primary
- Button Secondary
---
Ticket: https://jira.uitdatabank.be/browse/PPF-316
> PPF-316-Change button weight

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/FormElement.tsx
- resources/ts/Components/Page.tsx
- resources/ts/Components/RadioButtonGroup.tsx
- resources/ts/Pages/Integrations/New.tsx
- Changed styling on New Integration form
---
Ticket: https://jira.publiq.be/browse/PPF-276
> Changed styling on New Integration form

- resources/translations/nl.json
- Copy & typos
---
Ticket: https://jira.uitdatabank.be/browse/PPF-276
> Improve copy & fix typos

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/Footer.tsx
- resources/ts/Components/IntegrationCard.tsx
- resources/ts/Components/Link.tsx
- Correct links
---
Ticket: https://jira.uitdatabank.be/browse/PPF-278
> PPF-278-Add links

- app/Domain/Organizations/Organization.php
- app/Domain/Organizations/Repositories/EloquentOrganizationRepository.php
- app/Insightly/Listeners/CreateProjectWithOrganization.php
- app/Insightly/Serializers/OrganizationSerializer.php
- app/Nova/Resources/Organization.php
- database/migrations/2024_03_21_095339_make_invoice_email_nullable_on_organizations.php
- Made invoicing email optional as preparation for revised activation flows
---
Ticket: https://jira.uitdatabank.be/browse/PPF-314
> PPF-314 Make invoicing email optional

- resources/ts/Components/ButtonPrimary.tsx
- ButtonPrimary height
---
Ticket: https://jira.uitdatabank.be/browse/PPF-323
> PPF-323-Fix button height

- resources/ts/Components/FormElement.tsx
- resources/ts/Components/RadioButtonGroup.tsx
- resources/ts/Pages/Integrations/New.tsx
- resources/ts/types/Theme.ts
- Design tweaks in new integration form
---
Ticket: https://jira.publiq.be/browse/PPF-276
> Design tweaks in new integration form

- app/Domain/Integrations/Controllers/IntegrationController.php
- tests/Domain/Integrations/Controllers/IntegrationControllerTest.php
- After creating an integration, redirect the user to the integration detail page
---
Ticket: https://jira.uitdatabank.be/browse/PPF-312
> PPF-312-Redirect the user to the integration detail page

- app/Domain/Integrations/Models/IntegrationModel.php
- app/Domain/Integrations/Repositories/EloquentIntegrationRepository.php
- app/Domain/Integrations/Repositories/IntegrationRepository.php
- app/Nova/Actions/ApproveIntegration.php
- app/Nova/Resources/Auth0Client.php
- app/Nova/Resources/Integration.php
- app/Nova/Resources/UiTiDv1.php
- Added Nova action to approve integration
- Take into account the `ActionRequest` to avoid a 403 when showing the possible actions
---
Ticket: https://jira.uitdatabank.be/browse/PPF-335
> PPF-335 Add Nova action to approve integration

- app/Domain/Integrations/Controllers/IntegrationController.php
- resources/ts/Components/Integrations/Detail/IntegrationSettings.tsx
- tests/Domain/Integrations/Controllers/IntegrationControllerTest.php
- Confirm leave dialog
---
Ticket: https://jira.uitdatabank.be/browse/PPF-325
> PPF-325-Fix confirm leave dialog

- resources/ts/Components/Card.tsx
- ul alignment
---
Ticket: https://jira.uitdatabank.be/browse/PPF-336
> PPF-336-Fix ul alignment

- app/Domain/Contacts/Models/ContactKeyVisibilityModel.php
- app/Domain/Contacts/Repositories/ContactKeyVisibilityRepository.php
- app/Domain/Contacts/Repositories/EloquentContactKeyVisibilityRepository.php
- app/Domain/Integrations/Controllers/IntegrationController.php
- app/Domain/Integrations/Repositories/EloquentIntegrationRepository.php
- app/Nova/Resources/ContactKeyVisibility.php
- app/Providers/AppServiceProvider.php
- database/migrations/2024_03_25_141332_create_contacts_key_visibility_table.php
- tests/Domain/Integrations/Controllers/IntegrationControllerTest.php
- Added table to store default keys for contacts and use this information when creating a new integration with the integration controller
---
Ticket: https://jira.uitdatabank.be/browse/PPF-337
> PPF-337 Add table to store default keys for contacts

- e2e/tests/integrations/create-integration-as-integrator.test.ts
- e2e/tests/integrations/view-integrations-in-overview.test.ts
- [test as an integrator I can create an integration](https://github.com/cultuurnet/publiq-platform/commit/49ff7e244b4b55ab6487446e7a4822808ff12978)
---
Ticket: https://jira.publiq.be/browse/PPF-343
> PPF-343 - Add test as an integrator I can create an integration

- app/Nova/Resources/Auth0Client.php
- app/Nova/Resources/UiTiDv1.php
- Make the key sorting fix on the environment: 1. acc, 2. test, 3. prod
---
Ticket: https://jira.uitdatabank.be/browse/PPF-311
> PPF-311 Improve keys order

- app/Domain/Subscriptions/Policies/SubscriptionPolicy.php
- Made subscriptions editable again
---
Ticket: https://jira.uitdatabank.be/browse/PPF-340
> PPF-340 Make subscriptions editable again

- e2e/tests/integrations/create-integration-as-admin.test.ts
- e2e/tests/integrations/create-integration-as-integrator.test.ts
- package-lock.json
- package.json
- [faker js package for E2E tests](https://github.com/cultuurnet/publiq-platform/commit/e291536af5e7684ef720f3173dcff132bafb8921)
- [as an admin I can add contacts to a new integration](https://github.com/cultuurnet/publiq-platform/commit/5f73c6b8482419912eebff7097da0ef249879d7f)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-350
> PPF-350 - As an admin I can add contacts to a new integration

- e2e/tests/integrations/integrator-not-allowed-on-admin-pages.test.ts
- [e2e test: as Integrator I'm not allowed to see admin pages](https://github.com/cultuurnet/publiq-platform/commit/87d37395f86750642745fa898edc7752099c7cb6)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-346
> PPF-346 - Add test: as Integrator I'm not allowed to see admin pages

- e2e/tests/integrations/request-activation-as-integrator.test.ts
- [E2E test: as an integrator I can request activation](https://github.com/cultuurnet/publiq-platform/commit/fc829d397ff8ede4604252eee3b98cc52a0c3f26)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-352
> PPF-352 - Add E2E test: as an integrator I can request activation

- resources/ts/Components/Integrations/Detail/CredentialsLegacyAuthConsumers.tsx
- resources/ts/Components/UitIdWidget.tsx
- uitid widget application name
---
Ticket: https://jira.uitdatabank.be/browse/PPF-358
> PPF-358-Fix uitid widget copy

- resources/translations/nl.json
> Improve copy

- Jenkinsfile
---
Ticket: https://jira.uitdatabank.be/browse/PPF-349
> Add acceptance tests stage that can fail without failing the build

- Jenkinsfile
- Jenkinsfile: [step to install playwright & chromium dependencies](https://github.com/cultuurnet/publiq-platform/commit/343c7569be2cacb3ae2e39920d07574b062b3c6f)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-349
> PPF-349 - Add step to install playwright & chromium dependencies

- app/Domain/Integrations/Controllers/IntegrationController.php
- app/Domain/Integrations/FormRequests/StoreIntegrationRequest.php
- app/Domain/Integrations/IntegrationServiceProvider.php
- app/Domain/Integrations/Listeners/ActivateIntegration.php
- app/Domain/Integrations/Mappers/StoreIntegrationMapper.php
- app/Domain/Integrations/Models/IntegrationModel.php
- app/Domain/Integrations/Repositories/EloquentIntegrationRepository.php
- app/Domain/Integrations/Repositories/IntegrationRepository.php
- app/Insightly/Listeners/ActivateProject.php
- app/Nova/Actions/ActivateIntegration.php
- tests/Domain/Integrations/Controllers/IntegrationControllerTest.php
- tests/Domain/Integrations/Listeners/ActivateIntegrationTest.php
- tests/Domain/Integrations/Models/IntegrationModelTest.php
- tests/Domain/Integrations/Repositories/EloquentIntegrationRepositoryTest.php
- Added automatic activation for an integration with coupon code, basic plan and sapi or widget type
---
Ticket: https://jira.uitdatabank.be/browse/PPF-362
> PPF-362 Implement automatic activation

- app/Domain/Coupons/Coupon.php
- app/Domain/Integrations/Controllers/IntegrationController.php
- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/ActivationDialog.tsx
- resources/ts/Components/Integrations/Detail/BillingInfo.tsx
- resources/ts/Context/CouponInfo.tsx
- resources/ts/Pages/Integrations/Detail.tsx
- [Show price overview in activation dialog](https://github.com/cultuurnet/publiq-platform/commit/f799d0fc11b63985a373cc56481f790cf740fbf9)
- [Show coupon info on detail page](https://github.com/cultuurnet/publiq-platform/commit/b345037cdf69fec46752613886e4e5fff173b18d)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-314
Screenshots:
> PPF-314 - Show price total and coupon information

- resources/translations/en.json
- resources/translations/nl.json
- Link to slack channel
---
Ticket: https://jira.uitdatabank.be/browse/PPF-371
> PPF-371-Update link to slack channel

- resources/ts/Components/ActivationDialog.tsx
- resources/ts/Components/Integrations/Detail/BillingInfo.tsx
- resources/ts/types/Integration.ts
- [Check nullability of coupon](https://github.com/cultuurnet/publiq-platform/commit/f9c2fbded074fda3c0fcb01a0bfd8f17320b5ec2)
- Billing info error on coupon
---
Ticket: https://jira.uitdatabank.be/browse/PPF-379
> PPF-379 - Check nullability of coupon

- app/Nova/Resources/Integration.php
- [Set default sorting for integration resource to created_at desc](https://github.com/cultuurnet/publiq-platform/commit/b4abb0860186701d860ddcbb31619063867c5346)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-368
> PPF-368 - Sort integrations by creation date in admin

- e2e/tests/integrations/admin/activate-integration.test.ts
- e2e/tests/integrations/admin/approve-integration.test.ts
- e2e/tests/integrations/admin/block-integration.test.ts
- e2e/tests/integrations/admin/create-integration.test.ts
- e2e/tests/integrations/admin/create-integration.ts
- e2e/tests/integrations/integrator/create-integration.test.ts
- e2e/tests/integrations/integrator/create-integration.ts
- e2e/tests/integrations/integrator/request-activation.test.ts
- e2e/tests/integrations/integrator/request-activation.ts
- e2e/tests/types.ts
- e2e/tsconfig.json
> Use app types in e2e tests

- app/Domain/Integrations/FormRequests/StoreIntegrationRequest.php
- resources/ts/Pages/Integrations/New.tsx
- Create an integration (widgets OR search api, price plan = basic) with coupon
---
Ticket: https://jira.uitdatabank.be/browse/PPF-363
> PPF-363-Create an integration with coupon

- resources/translations/nl.json
> Improved copy (NL)

- e2e/tests/integrations/integrator/edit-integration.test.ts
- [Add test as an integrator I can edit an existing integration](https://github.com/cultuurnet/publiq-platform/commit/30ba281e3b21a9b98914023ebc9f2a46f8eb59c3)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-378
> PPF-378 - As an integrator I can edit an existing integration

- app/Domain/Coupons/Policies/CouponPolicy.php
- app/Nova/Resources/Coupon.php
- e2e/tests/integrations/admin/create-coupon.test.ts
- e2e/tests/integrations/admin/edit-integration.test.ts
- e2e/tests/integrations/integrator/edit-integration.test.ts
- [test: As an admin I can create a coupon](https://github.com/cultuurnet/publiq-platform/pull/974/commits/1ce5c687a357f7b6a08f7dd8bd77daf105e04bf0)
- [Allow creation of coupons](https://github.com/cultuurnet/publiq-platform/pull/974/commits/27a88e230499e32ce72807d4ca1e9fc1213216fd)
- [Fix types](https://github.com/cultuurnet/publiq-platform/pull/974/commits/e6c4157b41acb139fd26470d667371c64c9c0907)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-382
> PPF-382 - Allow creation of coupons

- resources/ts/Components/IntegrationCard.tsx
- Integration overview key visibility
---
Ticket: https://jira.uitdatabank.be/browse/PPF-381
> PPF-381-Fix integration overview key visibility

- resources/ts/Components/Alert.tsx
- resources/ts/Components/Integrations/Detail/BillingInfo.tsx
- resources/ts/Components/Tooltip.tsx
- resources/ts/Pages/Integrations/Detail.tsx
-Styling
Tooltip:
---
Ticket: https://jira.uitdatabank.be/browse/PPF-360
> PPF-360-Improve styling

- app/Domain/Integrations/Controllers/IntegrationController.php
- resources/ts/Components/Integrations/Detail/CredentialsAuthClients.tsx
- tests/Domain/Integrations/Controllers/IntegrationControllerTest.php
- Key visibility upgrade
---
Ticket: https://jira.uitdatabank.be/browse/PPF-376
> PPF-276-Implement key visibility upgrade

- resources/ts/Components/Integrations/Detail/Credentials.tsx
- Credentials key visibility
---
Ticket: https://jira.uitdatabank.be/browse/PPF-381
> PPF-381-Fix credentials key visibility

- app/Domain/Integrations/Integration.php
- app/Domain/Integrations/Models/IntegrationModel.php
- app/Domain/KeyVisibilityUpgrades/KeyVisibilityUpgrade.php
- app/Domain/KeyVisibilityUpgrades/Models/KeyVisibilityUpgradeModel.php
- Exposed key visibility upgrade on Integration
---
Ticket: https://jira.uitdatabank.be/browse/PPF-389
> PPF-389 Expose key visibility upgrade

- app/Domain/Integrations/Integration.php
- [Fix error key visibility](https://github.com/cultuurnet/publiq-platform/commit/dbb49279f999bf4aa1a33968e4ff18cd083fa586)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-389
> PPF-389 - Fix error key visibility

- resources/ts/Components/Integrations/Detail/CredentialsAuthClients.tsx
-Key visibility upgrade
---
Ticket: https://jira.uitdatabank.be/browse/PPF-376
> PPF-376-Fix key visibility upgrade

- resources/translations/en.json
- resources/translations/nl.json
- terms of use link
---
Ticket: https://jira.uitdatabank.be/browse/PPF-395
> PPF-395 Correct terms of use link

- .github/workflows/ci.yml
- routes/web.php
- tests/Domain/Integrations/Controllers/IntegrationControllerTest.php
- [Add detail page under access-integration gate](https://github.com/cultuurnet/publiq-platform/pull/988/commits/6e5131cc3eb77b875ad36b335144cdc5360ec25e)
- [Add test](https://github.com/cultuurnet/publiq-platform/pull/988/commits/111cd619a51cb655a022028421840d7164effd2a)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-398
> PPF-398 - Protect detail page integration

- e2e/tests/integrations/admin/approve-integration.test.ts
- e2e/tests/integrations/admin/edit-integration.test.ts
- [a timeout to make sure "approve" action is there](https://github.com/cultuurnet/publiq-platform/commit/1c7f7ea81c150ce8cf5827b9fbbbed9e64c8339a)
- [new test: as an admin I can edit an existing integration](https://github.com/cultuurnet/publiq-platform/commit/b8978e259ed78d5d0d0a96be733cd765df7dba37)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-377
> PPF-377 - Test: As an admin I can edit an existing integration

- app/Domain/Auth/AuthServiceProvider.php
- tests/ActingAsUser.php
- tests/Domain/Integrations/Controllers/IntegrationControllerTest.php
- tests/TestCase.php
- [Add check for admins in access-integration gate](https://github.com/cultuurnet/publiq-platform/commit/e6ff8ebc0f90b1c1f3a6ab22fcdf641adf06b93f)
- [Test admin vs normal user](https://github.com/cultuurnet/publiq-platform/commit/048c167f6f9a77f7179909c5ee39274576757813)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-398
> PPF-398 - Grant access to admin for integrations

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Pages/Integrations/New.tsx
- Move copy about payment to price plan section, and do not show it for integration type "entry api"
---
Ticket: https://jira.uitdatabank.be/browse/PPF-401
> PPF-401 - Move copy about payment to price plan section, and do not show it for integration type "entry api"

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Pages/Integrations/New.tsx
- Show alert when new integration form has errors
Screenshot:
---
Ticket: https://jira.uitdatabank.be/browse/PPF-400
> PPF-400 - Show alert when new integration form has errors

- resources/ts/Components/RadioButtonGroup.tsx
- Improve contrast of description on RadioButtonGroup
Screenshot:
---
Ticket: https://jira.uitdatabank.be/browse/PPF-392
> PPF-392 - Improve contrast of description on RadioButtonGroup

- e2e/tests/integrations/admin/create-coupon.test.ts
- e2e/tests/integrations/admin/create-coupon.ts
- e2e/tests/integrations/integrator/create-integration-with-coupon.test.ts
- e2e/tests/integrations/integrator/create-integration.ts
- [optional couponCode param to create-integration](https://github.com/cultuurnet/publiq-platform/commit/0574232d6311d70d5b6476156d8650c56a3632f4)
- [test As an integrator I can create an integration with a coupon code](https://github.com/cultuurnet/publiq-platform/commit/6821abe23f4be04da60f7f536116e2f745e283b1)
- [Move create coupon to helper function](https://github.com/cultuurnet/publiq-platform/commit/e2583be69644ab39fcc5e15f951cfd1ebb9300e7)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-382
> PPF-382 - E2E: As an integrator I can create an integration with coupon

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/Integrations/Detail/BillingInfo.tsx
- resources/ts/types/Organization.ts
- [invoiceEmail to translation files](https://github.com/cultuurnet/publiq-platform/commit/d8ee4896c1622e44a1d6a5a3e08fd96569ebd639)
- [nvoiceEmail edit field on BillingInfo](https://github.com/cultuurnet/publiq-platform/commit/90dda1e480dda5c0762ee23e2bb7522b51c265de)
- [typo in Organization type](https://github.com/cultuurnet/publiq-platform/commit/467db10677f633260db0ce0740f7b15a30f5cefc)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-405
> PPF-405 - Make e-mail address accounting editable

- resources/ts/Components/UitIdWidget.tsx
- [Fix my integrations link uitid widget](https://github.com/cultuurnet/publiq-platform/commit/040e07a244eedcddd94ac74f3837ce361acb72ba)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-399
> PPF-399 - Fix my integrations link uitid widget

- app/Domain/Integrations/Controllers/IntegrationController.php
- app/Domain/Integrations/Repositories/EloquentIntegrationRepository.php
- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/Alert.tsx
- resources/ts/Components/Integrations/Detail/ContactInfo.tsx
-  guardUserIsContact
- Contact info alert
---
Ticket: https://jira.uitdatabank.be/browse/PPF-408
> PPF-408-An integrator is able to remove him/herself from the integration

- resources/translations/en.json
Missing links for roadmap & release notes
---
Ticket: https://jira.uitdatabank.be/browse/PPF-415
> Add missing links

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/Integrations/Detail/ContactInfo.tsx
- Contact description
---
Ticket: https://jira.uitdatabank.be/browse/PPF-408
> PPF-408-Delete duplicate sentence

- resources/ts/Components/RadioButtonGroup.tsx
- resources/ts/Pages/Integrations/New.tsx
- Radio buttons
---
Ticket: https://jira.uitdatabank.be/browse/PPF-409
> PPF-409-Add radio buttons

- resources/translations/en.json
- resources/translations/nl.json
* Correct link to style guide
---
Ticket: https://jira.uitdatabank.be/browse/PPF-20
> Add correct link to style guide

- app/Exceptions/Handler.php
- 500 error
---
Ticket: https://jira.uitdatabank.be/browse/PPF-386
> PPF-386-Fix 500 error

- resources/ts/Pages/Error.tsx
- Back button
---
Ticket: https://jira.uitdatabank.be/browse/PPF-424
> PPF-424-Fix back button

- config.sh
- `config.sh`:  Add `host.docker.internal` via `make config`
---
Ticket: https://jira.uitdatabank.be/browse/III-6155
> III-6155 update /etc/hosts via config

- app/Console/Commands/Migrations/MigrateProjects.php
- app/Console/Commands/Migrations/MigrationProject.php
- Tweak migration and handle unique constraint exception on key visibility
---
Ticket: https://jira.uitdatabank.be/browse/PPF-282
> PPF-282 Tweak migration

- resources/ts/Components/IntegrationCard.tsx
> Fix widget builder button

- app/Keycloak/Client/KeycloakClient.php
- app/Keycloak/TokenStrategy/ClientCredentials.php
- tests/Keycloak/TokenStrategy/ClientCredentialsTest.php
Moved HttpClient away as direct dependency from the KeycloakClient, and created a new seperate KeycloakClient.
In the future this class will also be responsible to setting the correct token.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-435
> PPF-435 Create new KeycloakClient class

- app/Console/Commands/Migrations/MigrateProjects.php
- Use unique id for imported contact
> Use unique id for imported contact

- resources/ts/Components/ContactsTableContent.tsx
- resources/ts/Components/Integrations/Detail/ContactInfo.tsx
- [Hide functional and technical contact if one is missing](https://github.com/cultuurnet/publiq-platform/commit/fea92c004046cf59efa96c01d9e46a3111d2a3af)
- missing contacts crashes the frontend
---
Ticket: https://jira.uitdatabank.be/browse/PPF-443
> PPF-443 - Hide functional and technical contact if one is missing

- app/Insightly/Pipelines.php
- Fixed integer values pipeline env variables
> Fix integer values pipeline env variables

- app/Console/Commands/Migrations/MigrateProjects.php
- Avoid using UiTiD but create a new contributor
> Avoid using UiTiD but create a new contributor

- config/nova.php
> Add Renate as admin

- config/nova.php
> Add Tessa as admin

- app/Keycloak/Exception/KeyCloakApiFailed.php
- app/Keycloak/Service/ApiClient.php
- tests/Keycloak/Service/ApiClientTest.php
Add scope (widgets / sapi3 / entry api) to Keycloak client
---
Ticket: https://jira.uitdatabank.be/browse/PPF-435
> PPF-435 Add scope to client

- config/nova.php
> Add Delfien

- config/nova.php
> Add Toon as admin

- config/nova.php
> Add Karen as admin

- app/Domain/Integrations/Integration.php
- app/Domain/Integrations/Models/IntegrationModel.php
- app/Domain/Integrations/Repositories/EloquentIntegrationRepository.php
- app/Domain/Integrations/Website.php
- app/Insightly/Serializers/CustomFields/WebsiteSerializer.php
- app/Insightly/Serializers/OpportunitySerializer.php
- app/Insightly/Serializers/ProjectSerializer.php
- app/Nova/Resources/Integration.php
- database/migrations/2024_05_17_120330_add_website_to_integrations_table.php
- tests/Domain/Integrations/Repositories/EloquentIntegrationRepositoryTest.php
- tests/Insightly/Resources/InsightlyOpportunityResourceTest.php
- tests/Insightly/Resources/InsightlyProjectResourceTest.php
- Added optional website to integration and store it inside Insightly
---
Ticket: https://jira.uitdatabank.be/browse/PPF-468
> PPF-468 Add optional website to integration

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Pages/Integrations/New.tsx
- Copy tweaks for UiTPAS integration type/plan
---
Ticket: https://jira.publiq.be/browse/PPF-457
> Copy tweaks for UiTPAS integration type/plan

- app/Keycloak/CachedKeycloakClientStatus.php
- app/Keycloak/Client/ApiClient.php
- app/Keycloak/Client/KeycloakApiClient.php
- app/Keycloak/Events/ClientBlocked.php
- app/Keycloak/Events/ClientUnblocked.php
- app/Keycloak/Jobs/BlockClient.php
- app/Keycloak/Jobs/BlockClientHandler.php
- app/Keycloak/Jobs/UnblockClient.php
- app/Keycloak/Jobs/UnblockClientHandler.php
- app/Keycloak/KeycloakServiceProvider.php
- app/Keycloak/Listeners/BlockClients.php
- app/Nova/ActionGuards/Keycloak/BlockKeycloakClientGuard.php
- app/Nova/ActionGuards/Keycloak/UnblockKeycloakClientGuard.php
- app/Nova/Actions/Keycloak/BlockKeycloakClient.php
- app/Nova/Actions/Keycloak/UnblockKeycloakClient.php
- app/Nova/Resources/KeycloakClient.php
- tests/Keycloak/CachedKeycloakClientStatusTest.php
- tests/Keycloak/Jobs/BlockClientHandlerTest.php
- tests/Keycloak/Jobs/UnblockClientHandlerTest.php
- tests/Keycloak/Listeners/BlockClientsTest.php
- tests/Keycloak/Service/KeycloakApiClientTest.php
- tests/Nova/ActionGuards/Keycloak/BlockKeycloakClientGuardTest.php
- tests/Nova/ActionGuards/Keycloak/UnblockKeycloakClientGuardTest.php
This change is based on a meeting and feedback from Corneel.
- In the context of Keycloak, change every reference from Disable to block
- In the context of Keycloak, change every reference from Enable to unblock / Active
---
Ticket: https://jira.uitdatabank.be/browse/PPF-500
> PPF-500 Rename disable to block

- app/Domain/Integrations/Models/IntegrationModel.php
- app/Nova/Resources/Integration.php
- Made website required in Nova admin when UiTPAS integration
---
Ticket: https://jira.uitdatabank.be/browse/PPF-491
> PPF-491 Make website required when UiTPAS integration

- app/Console/Commands/SearchUiTPASOrganizer.php
- app/Search/Sapi3/Sapi3SearchService.php
- app/Search/Sapi3/SearchService.php
- app/Search/SearchServiceProvider.php
- Moved interface to fix Jenkins build error
> Move interface to fix Jenkins build error

- app/Domain/Integrations/IntegrationServiceProvider.php
- app/Domain/Integrations/Models/IntegrationModel.php
- app/Domain/Integrations/Models/OrganizerModel.php
- app/Domain/Integrations/Organizer.php
- app/Domain/Integrations/Policies/OrganizerPolicy.php
- app/Domain/Integrations/Repositories/EloquentOrganizerRepository.php
- app/Domain/Integrations/Repositories/OrganizerRepository.php
- app/Nova/Actions/AddOrganizer.php
- app/Nova/Resources/Integration.php
- app/Nova/Resources/Organizer.php
- database/migrations/2024_05_24_160712_create_organizers_table.php
- tests/Insightly/Listeners/SyncContactTest.php
- Added simple action to add an organizer based on UUID to an Integration
- This is a very simple approach without an AJAX call to get the organizer based on a name. This AJAX approach is nice to have for the admin.
- An extra `name` column count be useful to eliminate extra calls to UDB3
---
Ticket: https://jira.uitdatabank.be/browse/PPF-482
> PPF-482 As admin I can add an organizer

- app/Nova/Resources/Integration.php
- Use dependsOn to make the website required when switching to UiTPAS
---
Ticket: https://jira.uitdatabank.be/browse/PPF-491
> PPF-491 Use dependsOn to make website required when switching to UiTPAS

- app/Domain/Integrations/Integration.php
Add keycloak clients to Integration:toArray() to expose to the API
---
Ticket: https://jira.uitdatabank.be/browse/PPF-493
> PPF-493 Integration expose keycloak clients

- app/Notifications/Slack/SlackMessageBuilder.php
> Change icon for integration create

- app/Nova/Resources/Integration.php
- Enable searching on keys UiTiD and Auth0
- Also needs to be done for Keycloack
---
Ticket: https://jira.uitdatabank.be/browse/PPF-507
> PPF-507 Enable searching on keys UiTiD and Auth0

- app/Nova/Resources/Integration.php
- app/Providers/AuthServiceProvider.php
- Enable UDB3 Organizers only for UiTPAS
- Bootstrap Organizers policy
---
Ticket: https://jira.uitdatabank.be/browse/PPF-482
> PPF-482 Enable Organizers only for UiTPAS

- .env.ci
- app/Auth0/Auth0Config.php
- app/Auth0/Auth0ServiceProvider.php
- app/Keycloak/KeycloakConfig.php
- app/Keycloak/KeycloakServiceProvider.php
- app/Nova/Resources/Integration.php
- config/auth0.php
- Added a flag (actually I renamed the flag and made it broader) to completly hide everything related to auth0
- Added Keycloak to Integration::searchableColumns()
---
Ticket: https://jira.uitdatabank.be/browse/PPF-508
> PPF-508 Add flag to hide auth0

- app/Keycloak/KeycloakServiceProvider.php
- app/Keycloak/Listeners/UnblockClients.php
- tests/Keycloak/Listeners/UnblockClientsTest.php
When you unblock an entire integration, also unblock all Keycloak clients.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-485
> PPF-485 mass unblock keycloak status

- app/Domain/Auth/Controllers/LogoutController.php
- To make logout work in Keycloak we needed a different URL structure
---
Ticket: https://jira.uitdatabank.be/browse/PPF-450
> PPF-450 Fix logout for keycloak

- .env.ci
- app/Auth0/Auth0ServiceProvider.php
- app/Domain/Auth/Controllers/LogoutController.php
- app/Keycloak/KeycloakConfig.php
- app/Keycloak/KeycloakServiceProvider.php
- app/Nova/Resources/Integration.php
- app/Providers/AuthServiceProvider.php
- config/auth0.php
- config/keycloak.php
Use different env values to configure auth-flow depending if `IS_KEYCLOAK_ENABLED` is true.
https://github.com/cultuurnet/appconfig/pull/693
---
Ticket: https://jira.uitdatabank.be/browse/PPF-450
> PPF-450 Add different config for auth0 vs keycloak

- app/Keycloak/Converters/IntegrationUrlConverter.php
- tests/Keycloak/Converters/IntegrationToKeycloakClientConverterTest.php
- tests/Keycloak/Converters/IntegrationUrlConverterTest.php
- To split logout urls you need 2 ## not 1.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-525
> PPF-525 Fix # for logout urls

- app/Search/Sapi3/Sapi3SearchService.php
- Search on UiTPAS label with wildcard
---
Ticket: https://jira.uitdatabank.be/browse/PPF-460
> PPF-460 Search on UiTPAS label with wildcard

- resources/translations/en.json
* copy for pending state
---
Ticket: https://jira.uitdatabank.be/browse/PPF-539
> Add copy for pending status

- resources/ts/Components/ActivationRequest.tsx
- Activation request gap
---
Ticket: https://jira.uitdatabank.be/browse/PPF-532
> PPF-532-Add gap

- resources/ts/Components/CopyText.tsx
- resources/ts/Components/IntegrationCard.tsx
- resources/ts/Components/Integrations/Detail/CredentialsAuthClients.tsx
- resources/ts/Components/Integrations/Detail/CredentialsLegacyAuthConsumers.tsx
- resources/ts/Components/Tooltip.tsx
- Client secret hide/show feature
---
Ticket: https://jira.uitdatabank.be/browse/PPF-501
> PPF-501-Client secret visibility

- app/Domain/Integrations/Controllers/IntegrationController.php
- app/Domain/Integrations/Repositories/EloquentOrganizerRepository.php
- app/Domain/Integrations/Repositories/OrganizerRepository.php
- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/Integrations/Detail/ContactInfo.tsx
- resources/ts/Components/Integrations/Detail/OrganizersInfo.tsx
- routes/web.php
- Added ability to remove organizer off integration
---
Ticket: https://jira.publiq.be/browse/PPF-464
> Added ability to remove organizer off integration

- app/Search/Sapi3/Sapi3SearchService.php
- Fixed findUiTPASOrganizers only returning first organizer from query
> Fixed findUiTPASOrganizers only returning first organizer from query

- app/Domain/Integrations/Models/IntegrationModel.php
I know I just merged PR https://github.com/cultuurnet/publiq-platform/pull/1263, but I thought of a better solution.
This avoids the side effects described in the previous PR.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-553
> PPF-553 A better fix

- app/Domain/Integrations/Controllers/IntegrationController.php
- resources/ts/Components/Integrations/Detail/OrganizersInfo.tsx
- Fixed dummy test organizer not appearing in the list
- Fixed incorrect Test/Live split of organizers
- Fixed styling of organizer cards
---
Ticket: https://jira.publiq.be/browse/PPF-462
> Fixes to organizer info tab

- app/Domain/Integrations/Models/IntegrationModel.php
- app/Nova/Resources/Integration.php
- Use `canSee` to load organizers for UiTPAS integrations
---
Ticket: https://jira.uitdatabank.be/browse/PPF-553
> PPF-553 Use `canSee` to load organizers

- app/Providers/NovaServiceProvider.php
- Created a minimal vertical menu with just the resources
---
Ticket: https://jira.uitdatabank.be/browse/PPF-524
> PPF-524 Create a minimal vertical menu with just the resources

- resources/ts/Components/Integrations/Detail/OrganizersInfo.tsx
- Remove currently nonfunctional organizer edit button
---
Ticket: https://jira.publiq.be/browse/PPF-558
> Remove currently nonfunctional organizer edit button

- e2e/tests/integrations/integrator/edit-integration.test.ts
- Fixed E2E test by removing URLs because only first-party integrations have this option
---
Ticket: https://jira.uitdatabank.be/browse/PPF-506
> PPF-506 Remove URLs for third party integrations

- e2e/tests/integrations/integrator/create-integration.ts
- Fixed creation of Entry API in E2E because UiTPAS is now the first
---
Ticket: https://jira.uitdatabank.be/browse/PPF-506
> PPF-506 Fix creation of Entry API in E2E because UiTPAS is now the first

- app/Nova/Resources/Integration.php
- Allowed only key visibility v2 when creating UiTPAS integration in backend
---
Ticket: https://jira.uitdatabank.be/browse/PPF-555
> PPF-555 Allow only key visibility v2 when creating UiTPAS integration in backend

- app/Domain/Integrations/Models/IntegrationModel.php
- Added casts to integration model
---
Ticket: https://jira.uitdatabank.be/browse/PPF-555
> PPF-555 Add casts to integration model

- app/Domain/Integrations/Models/IntegrationModel.php
- app/Domain/Integrations/Repositories/EloquentIntegrationRepository.php
- tests/Domain/Integrations/Repositories/EloquentIntegrationRepositoryTest.php
- Used integration eloquent model creating event to set key visibility
---
Ticket: https://jira.uitdatabank.be/browse/PPF-555
> PPF-555 Use creating event to set key visibility

- app/Mails/MailManager.php
- app/Mails/MailServiceProvider.php
- config/app.php
- tests/Mails/MailManagerTest.php
Sent mail when integration is activated
---
Ticket: https://jira.uitdatabank.be/browse/PPF-56
> PPF-56 Send mail when integration is activated

- Makefile
- Fix e2e commands in makefile
> Fix e2e commands in makefile

- e2e/tests/integrations/integrator/create-integration.ts
- resources/ts/Pages/Integrations/Detail.tsx
- Hide Organizers tab for non Uitpas integrations
---
Ticket: https://jira.publiq.be/browse/PPF-574
> Hide Organizers tab for non Uitpas integrations

- e2e/setup/auth.setup.ts
- e2e/tests/integrations/admin/activate-integration.test.ts
- e2e/tests/integrations/admin/block-integration.test.ts
- e2e/tests/integrations/admin/create-coupon.test.ts
- e2e/tests/integrations/admin/create-coupon.ts
- e2e/tests/integrations/admin/create-integration.test.ts
- e2e/tests/integrations/admin/create-integration.ts
- e2e/tests/integrations/admin/create-organization.test.ts
- e2e/tests/integrations/admin/create-organization.ts
- e2e/tests/integrations/admin/edit-integration.test.ts
- e2e/tests/integrations/integrator/create-integration-with-coupon.test.ts
- e2e/tests/integrations/integrator/create-integration.test.ts
- e2e/tests/integrations/integrator/create-integration.ts
- e2e/tests/integrations/integrator/create-widgets-integration.test.ts
- e2e/tests/integrations/integrator/edit-integration.test.ts
- playwright.config.ts
- Decrease workers due too high load
- Augment certain timeouts
- Never return page from factory function
- Move assertion url into factory functions (so we are sure this is always done)
- Make url assertions more correct
---
Ticket: https://jira.uitdatabank.be/browse/PPF-570
> PPF-570 - Make e2e tests less flaky

- app/Nova/Resources/Integration.php
- Loaded related resources eagerly on Integration resource
- Show missing key action only on detail page
---
Ticket: https://jira.uitdatabank.be/browse/PPF-588
> PPF-588 Improve performance integrations list

- composer.json
- composer.lock
- Move `barryvdh/laravel-debugbar` to required packages to be able to u…
---
Ticket: https://jira.uitdatabank.be/browse/PPF-588
> PPF-588 Enable debug bar

- database/migrations/2024_08_29_112833_index_integration_id_keycloak_clients.php
- Added an index on the `integration_id` column of `keycloak_clients`
---
Ticket: https://jira.uitdatabank.be/browse/PPF-588
> PPF-588 Add an index on the `integration_id` column of `keycloak_clients`

- app/Nova/Resources/Integration.php
- app/Nova/Resources/UdbOrganizer.php
- Rename `UdbOrganizer` resource to fix global search
---
Ticket: https://jira.uitdatabank.be/browse/PPF-589
> PPF-589 Rename UdbOrganizer resource to fix global search

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/Alert.tsx
- resources/ts/Components/Integrations/Detail/ContactInfo.tsx
- tailwind.config.js
- Warning variant
---
Ticket: https://jira.uitdatabank.be/browse/PPF-580
> PPF-580- Add warning variant

- resources/translations/en.json
- resources/ts/Components/Navigation.tsx
- Add Integration menu item
---
Ticket: https://jira.uitdatabank.be/browse/PPF-590
> Remove 'Add Integration' from the navigation bar

- app/Nova/Resources/Integration.php
- Filter and depend on integration type for subscriptions in admin UI
- Being able to create a integration with not matching type and subscription via admin UI
---
Ticket: https://jira.uitdatabank.be/browse/PPF-593
> PPF-593 - Filter and depend on integration type for subscriptions in admin UI

- resources/ts/Components/Card.tsx
- resources/ts/Components/IntegrationCard.tsx
- Integration type to the integration card
---
Ticket: https://jira.uitdatabank.be/browse/PPF-579
> PPF-579-Add the integration type to the integration card

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/WelcomeCard.tsx
- resources/ts/Components/WelcomeSection.tsx
- resources/ts/Pages/Integrations/Index.tsx
- Welcome section
- Welcome card
---
Ticket: https://jira.uitdatabank.be/browse/PPF-518
> PPF-518-Welcome section

- .gitignore
- app/Auth0/Auth0ClusterSDK.php
- app/Auth0/Auth0TenantSDK.php
- app/Console/Commands/Migrations/ContactCsvRow.php
- app/Console/Commands/Migrations/FixContacts.php
- app/Console/Commands/Migrations/MigrateContacts.php
- app/Console/Commands/Migrations/MigrateCoupons.php
- app/Console/Commands/Migrations/MigrateProjects.php
- app/Console/Commands/Migrations/ProjectCsvRow.php
- app/Console/Commands/ReadCsvFile.php
- app/Console/Commands/UiTPAS/MigrateUiTPAS.php
- app/Console/Commands/UiTPAS/UiTPASIntegration.php
- app/Console/Commands/UiTPAS/UiTPASIntegrationCsvRow.php
- Added script to migrate UiTPAS integrations from CSV file. This will import the basic integration details, contacts and keys
---
Ticket: https://jira.uitdatabank.be/browse/PPF-587
> PPF-587 Import UiTPAS integrations

- resources/translations/en.json
- resources/translations/nl.json
- link to terms of use
---
Ticket: https://jira.uitdatabank.be/browse/PPF-600
> Update terms of use link

- resources/ts/Pages/Integrations/Index.tsx
- Fixed Welcome state showing for empty search results
---
Ticket: https://jira.publiq.be/browse/PPF-599
> Fixed Welcome state showing for empty search results

- public/503.php
Added a Maintenance page for the Keycloak migration.
> Maintenance page for Keycloak migration

- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Components/IntegrationCard.tsx
- Added link to styleguide on Search API integration cards
---
Ticket: https://jira.publiq.be/browse/PPF-602
> Added link to styleguide on Search API integration cards

- public/503.php
- Changed order of languages
- Title is now in dutch
> switch dutch / english sentences + title in dutch

- resources/translations/en.json
- resources/translations/nl.json
- Ensure links in Welcome section point to current environment
---
Ticket: https://jira.publiq.be/browse/PPF-598
> Ensure links in Welcome section point to current environment

- resources/ts/Components/Integrations/Detail/Credentials.tsx
- Fix hasCredentials
---
Ticket: https://jira.uitdatabank.be/browse/PPF-615
> PPF-615 - Fix credential polling

- app/Console/Commands/UiTPAS/MigrateUiTPAS.php
- app/Console/Commands/UiTPAS/UiTPASIntegrationCsvRow.php
- Disable all events to prevent sending mails
- Fixed contact field order
---
Ticket: https://jira.uitdatabank.be/browse/PPF-620
> PPF-620 Fix UiTPAS imports

- nova_users.php
Added our new awesome colleague as an admin in Publiq Platform
> Add ben gabriels to nova users

- app/Console/Commands/Migrations/MigrateAuth0ToKeycloakClients.php
- tests/Console/Commands/Migrations/MigrateAuth0ToKeycloakClientsTest.php
I now look at the realm instead of the id for client matches. 
For more details see the ticket description.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-631
> PPF-631 Look at Realm instead of id for matches

- app/Domain/Integrations/Integration.php
- app/Nova/Resources/Auth0Client.php
- app/Nova/Resources/KeycloakClient.php
- app/Nova/Resources/UiTiDv1.php
- `app/Domain/Integrations/Integration`: Add `isKeyVisibleForEnvironment()`
- `app/Nova/Resources/Auth0Client`: Add column with `Visible for integrator` in adminPanel.
- `app/Nova/Resources/KeycloakClient`: Add column with `Visible for integrator` in adminPanel.
- `app/Nova/Resources/UiTiDv1`: Add column with `Visible for integrator` in adminPanel.
- `KeyVisibility` is now more clear for Admins.
---
Ticket: https://jira.publiq.be/browse/PPF-452
> PPF-452 Make key visibility more clear for admins

- public/503.php
- `public/503.php`: Update back-available dateTime for Keycloak production deploy
---
> Update dates for Keycloak production deploy

- e2e/tests/integrations/admin/activate-integration.test.ts
- e2e/tests/integrations/admin/approve-integration.test.ts
- Do a case-sensitive match for "active"
---
Ticket: https://jira.uitdatabank.be/browse/PPF-506
> PPF-506 Do a case-sensitive match for "active"

- e2e/tests/integrations/admin/activate-integration.test.ts
- e2e/tests/integrations/admin/approve-integration.test.ts
- e2e/tests/integrations/admin/block-integration.test.ts
- Improved status selector
---
Ticket: https://jira.uitdatabank.be/browse/PPF-506
> PPF-506 Improve status selector

- app/Nova/Resources/Auth0Client.php
- app/Nova/Resources/KeycloakClient.php
- app/Nova/Resources/UiTiDv1.php
- Move the "Visible for Integrator" column to after the "Status" column.  
- Change the text color for visible items to normal black.
- Set the text color for not visible items to a light grey.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-637
> PPF-637 Change visibility and order for the integrator

- resources/ts/Components/Dialog.tsx
- [Always make dialog scrollable](https://github.com/cultuurnet/publiq-platform/commit/43a7bd14fdbdee6bd3908a75e3ca7ece144bef74)
- [Block scrolling of body when dialog is open](https://github.com/cultuurnet/publiq-platform/commit/138c3515af256aa8f0fd270fe5ebd063c27233e2)
- scroll activation dialog
---
Ticket: https://jira.uitdatabank.be/browse/PPF-636
> PPF-636 - Fix scroll activation dialog

- app/Auth0/Auth0ServiceProvider.php
- Removed the Auth0 singletons
---
Ticket: https://jira.uitdatabank.be/browse/III-6401
> III-6401 Remove the Auth0 singletons

- app/Domain/Integrations/Models/IntegrationModel.php
- app/Domain/Integrations/Repositories/EloquentIntegrationRepository.php
- app/Nova/Filters/AdminInformationFilter.php
- tests/Domain/Integrations/Repositories/EloquentIntegrationRepositoryTest.php
- Take into account hold state for reminder mails
---
Ticket: https://jira.uitdatabank.be/browse/PPF-564
> PPF-564 Take into account hold state for reminder mails

- app/Domain/Mail/MailManager.php
Gave mailmanager interface ShouldQueue to it queues on Horizon.
> Gave mailmanager interface ShouldQueue to it queues.

- app/Nova/Resources/Integration.php
- e2e/tests/integrations/admin/activate-integration.test.ts
- e2e/tests/integrations/admin/approve-integration.test.ts
- e2e/tests/integrations/admin/block-integration.test.ts
- Put `Admin Information` panel in a more logical place
- Fix Laravel Nova 5 random dropdown issue
- Avoid redirecting to active page which causes issues in Laravel Nova 5
> Fix e2e tests

- package-lock.json
- package.json
- Update react-dom types this wasn't updated by dependabot when updating other react versions
Related PR: https://github.com/cultuurnet/publiq-platform/pull/1602
> Update react-dom types

- .gitignore
- lib/tasks/build.rake
---
Ticket: https://jira.uitdatabank.be/browse/PPF-661
> Add 'php artisan nova:publish' to build process

- README.md
- `README.md`: Added info about dependabot
---
> Add info about dependabot

- app/Domain/Integrations/Controllers/IntegrationController.php
- resources/translations/en.json
- resources/translations/nl.json
- resources/ts/Pages/Integrations/New.tsx
- routes/web.php
- Fix create uitpas integration
- [Fix urls to create uitpas integration](https://github.com/cultuurnet/publiq-platform/pull/1733/commits/d8ad680341aff034e517e6020350c8052d9f6b3c)
- [Always set and validate type on the backend](https://github.com/cultuurnet/publiq-platform/pull/1733/commits/0b0b2a8823b8f3345c5dce0289c513c52ab5c4ea)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-672
> PPF-672 - Fix create uitpas integration

- .github/CODEOWNERS
- Removed Simon from Code Owners
> Remove Simon from Code Owners

- .github/CODEOWNERS
- Removed Paul & Emma from codeowners
> Remove Paul & Emma

- app/Nova/Filters/UdbOrganizerStatusFilter.php
- app/Nova/Resources/UdbOrganizer.php
- Added an overview page for admins to quickly see (pending) request of organisations. Request by Jean-Marie.
- Added created at date on UdbOrganizer resource in admin
- Small visual improvement when UDB organizer name is not found, stopped displaying a broken link.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-688
> PPF-688 Admin overview page udb organisations

- app/Domain/Integrations/Mappers/UdbOrganizerMapper.php
> Use correct `UdbUuid` type

- app/Domain/Integrations/GetIntegrationOrganizersWithTestOrganizer.php
- Use correct id part for organizer
> Use correct id part for organizer

- app/Nova/Actions/UdbOrganizer/RequestUdbOrganizer.php
- app/Search/Sapi3/Sapi3SearchService.php
- app/UiTPAS/Listeners/NotifyUdbOrganizerRequested.php
- app/UiTPAS/Listeners/SendMailForUdbOrganizer.php
- tests/UiTPAS/Listeners/NotifyUdbOrganizerRequestedTest.php
- tests/UiTPAS/Listeners/SendMailForUdbOrganizerTest.php
Finishing up some minor improvements based on feedback UiTPAS team.
- Immediately approve an udb organizer when added by admin, do not send email or slack message
- Add extra labels for the list of valid UiTPAS organizers, and make the list in frontend and backend consistent.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-668
> PPF-668 Improvements uitpas flow

- app/Http/Middleware/HandleInertiaRequests.php
- app/Nova/Actions/ActivateIntegration.php
- config/app.php
- config/coupons.php
- resources/ts/Pages/Integrations/New.tsx
- resources/ts/types/PageProps.ts
- `app/Http/Middleware/HandleInertiaRequests.php`: Update `key`
- `app/Nova/Actions/ActivateIntegration.php`: Update `key`
- `resources/ts/Pages/Integrations/New.tsx`: Update `key`
- `resources/ts/types/PageProps.ts`: Update `key`
- `config/coupons.php`
- no separate file for a feature flag
---
Ticket: https://jira.publiq.be/browse/PPF-692
> PPF-692 no separate file for a feature flag

- app/Nova/Resources/UdbOrganizer.php
> [Minor] Fix broken uitpas link

- app/Nova/Resources/UdbOrganizer.php
- Add link in admin screen on udb organizers to open integration (Request by @JurgenG )
---
Ticket: https://jira.uitdatabank.be/browse/PPF-700
> PPF-700 [Minor] Add link in admin screen to open integration

- app/Domain/Mail/MailManager.php
> Add check for flag

- resources/ts/Components/Integrations/Detail/BillingInfo.tsx
- [fallbacks for when address | organizer is undefined](https://github.com/cultuurnet/publiq-platform/commit/d9cde219400674a97ca4a004c3f0e3135bda9e7d)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-710
> PPF-710 - Add fallbacks for when address | organizer is undefined

- app/Domain/Integrations/Models/UdbOrganizerModel.php
- app/Nova/Resources/UdbOrganizer.php
- The integration field was broken if an integration no longer exists. 
- there might also be a missing Keycloak prod client, also triggering the issue.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-688
> PPF-688 Fixes bugs on admin overview screen
