cultuurnet/publiq-platform

package-lock.json, package.json
- Added a name to `package.json`. Otherwise the name in `package.lock` always gets overwritten to `html` when running `npm install`
=> Fix package name

database/migrations/2022_11_30_145724_update_action_events_table.php
- Length of column `user_id` in `action_events`
- Users with a migrated v1 account(with `UserId` like `auth0|<<UUID>>` can save items without getting an error.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-77
=> PPF-77 Bugfix migrated v1 accounts

composer.json
Removed the `keywords` from `composer.json` because:
- We won't publish this on packagist as it's an application, so no one will be searching on these keywords
- This app is not specific to UDB3
- The name "Publiq" is also in the name and description
---
(Just happened to notice this)
=> Remove incorrect/redundant keywords from composer.json

README.md, app/Exceptions/Handler.php
- Fixed `Auth::user()` being called (and crashing) when an exception is thrown in a CLI context.
- Fixed incorrect `make shell` in README (was later renamed to `make bash`)
=> Fix Sentry crash in CLI

.env.example, app/Domain/Auth/Controllers/Logout.php
- Added SSO support with uitinvlaanderen.be and uitpas.be (among others). To try it out, log in on https://acc.uitinvlaanderen.be and then go to http://localhost/admin. You will be logged in automatically. Note that if you go to http://localhost instead you won't be logged in automatically as the login flow is not triggered then. But if you go to http://localhost/integrations or http://localhost/integrations/create you should also be logged in automatically because those pages require a login. This behavior is consistent with the SSO behaviour on https://www.uitinvlaanderen.be and https://www.uitpas.be where you also need to explicitly click on the "user" icon or login button before the SSO is triggered. Important ⚠️ You MUST remove the `prompt=login` from the Auth0 login parameters in …
=> PPF-66 Add SSO support

app/Nova/Resources/Contact.php
- The ContactType field on a contact can not be changed during a contact update anymore
---
Ticket: https://jira.uitdatabank.be/browse/PPF-110
=> PPF-110 ContactType readonly

app/Insightly/Resources/InsightlyContactResource.php
- Removed usage of  http_build_query because using http_build_query will do a URL encode on the email address, resulting in a bad request.
=> Remove usage of http_build_query

app/Nova/Resources/Contact.php
- The integration field of a contact can no longer be updated. It's a read-only field.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-129
=> PPF-129 Integration field on contact update read-only

app/Insightly/Resources/ContactResource.php, app/Insightly/Resources/InsightlyContactResource.php, tests/Insightly/Resources/InsightlyContactResourceTest.php, tests/Insightly/Resources/InsightlyOpportunityResourceTest.php, tests/Insightly/Resources/InsightlyProjectResourceTest.php
- Added `get` method on `ContactResource`
- Added missing test for `get` on `OpportunityResource`
- Added missing test for `get` on `ProjectResource`
- Added missing test `updateWithCoupon` on `ProjectResource`
- Preparation for migration command
=> Add `get` method on `ContactResource`

app/Domain/Contacts/Repositories/EloquentContactRepository.php, tests/Domain/Contacts/Repositories/EloquentContactRepositoryTest.php
- Refactored saving a contact with the `ContactRepository` to either update a contact or create a new contact based on the id
- As preparation for the migration
- In the future more `save` methods will need to be refactored to do a `create` or `update`
=> Refactored save contact to either update or create

config/nova.php
- Used acc UiTiD email address for Corneel as Nova admin
=> Use acc UiTiD email address for Corneel as Nova admin

app/Nova/Resources/Integration.php
- Displayed coupon as a hyphen when missing
=> Display coupon as a hyphen when missing

app/Auth0/Auth0ClusterSDK.php, app/Console/Commands/Migrations/CreateMissingAuth0Clients.php
- Improved naming for the `CreateMissingAuth0Clients` command and removed the migration reference
=> Improve naming for the `CreateMissingAuth0Clients` command

app/Console/Commands/Migrations/CreateMissingUiTiDv1Consumers.php, app/Domain/Integrations/Models/IntegrationModel.php, app/UiTiDv1/UiTiDv1ClusterSDK.php, app/UiTiDv1/UiTiDv1EnvironmentNotConfigured.php
- Added command `CreateMissingUiTiDv1Consumers` to create missing UiTiD v1 Consumers
---
Ticket: https://jira.uitdatabank.be/browse/PPF-136
=> Add command to create missing UiTiD v1 consumers

tests/AssertRequest.php, tests/Insightly/Listeners/CreateProjectWithCouponTest.php, tests/Insightly/Listeners/SyncContactTest.php, tests/Insightly/Listeners/UnlinkContactTest.php, tests/Insightly/Resources/InsightlyOpportunityResourceTest.php, tests/Insightly/Resources/InsightlyProjectResourceTest.php, tests/UiTiDv1/Listeners/CreateConsumersTest.php
- All calls to  `MockObject::withConsecutive` have been replaced with `willReturnCallback` to make them compliant with phpunit10.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-148
=> Remove withConsecutive calls in tests

app/Domain/Integrations/Events/IntegrationActivatedWithOrganization.php, app/Domain/Integrations/Models/IntegrationModel.php, app/Domain/Integrations/Repositories/EloquentIntegrationRepository.php, app/Domain/Integrations/Repositories/IntegrationRepository.php, app/Insightly/Listeners/CreateProjectWithCoupon.php, app/Nova/Actions/ActivateIntegrationWithCoupon.php, app/Nova/Actions/ActivateIntegrationWithOrganization.php, app/Nova/Resources/Integration.php, database/migrations/2023_02_15_141921_add_organization_id_to_integrations_table.php, tests/Domain/Integrations/Repositories/EloquentIntegrationRepositoryTest.php
- Made it possible to activate an integration with an organization in Laravel Nova
- Added `organization_id` column on `integrations` table to store `BelongsTo` relation
- Made it possible to select an organization in the integration edit form
- Fixed issue with enabling of activate action
- In Laravel Nova we can require that the organization needs to be created first
- The sync to Insightly will be implemented in a follow-up pull request
---
Ticket: https://jira.uitdatabank.be/browse/PPF-97
=> PPF-97 Activate integration with organization (Laravel Nova part)

app/UiTiDv1/Listeners/UpdateConsumers.php, app/UiTiDv1/UiTiDv1ClusterSDK.php, app/UiTiDv1/UiTiDv1EnvironmentSDK.php, app/UiTiDv1/UiTiDv1ServiceProvider.php, tests/UiTiDv1/Listeners/BlockConsumersTest.php, tests/UiTiDv1/Listeners/UpdateConsumersTest.php
- Add listener `UpdateConsumers` which is bound to `IntegrationUpdated` and will update the name and description of the consumer according to the updated integration.
- The name could be changed depending on the outcome of https://jira.uitdatabank.be/browse/PPF-168
---
Ticket: https://jira.uitdatabank.be/browse/PPF-173
=> PPF-173 Update UiTiD v1 consumers when integration is updated

Makefile, README.md, app/Auth0/Auth0ClusterSDK.php, app/Auth0/Auth0ServiceProvider.php, app/Auth0/Auth0TenantSDK.php, app/Auth0/Listeners/UpdateClients.php, tests/Auth0/Listeners/UpdateClientsTest.php
- Add listener `UpdateClients` which is bound to `IntegrationUpdated` and will update the name of the client according to the updated integration.
- The name could be changed depending on the outcome of https://jira.uitdatabank.be/browse/PPF-168
---
Ticket: https://jira.uitdatabank.be/browse/PPF-172
=> PPF-172 Update name of Auth0 client

app/Domain/Integrations/Environment.php, app/Domain/Integrations/IntegrationUrl.php, app/Domain/Integrations/IntegrationUrlType.php, app/Domain/Integrations/Models/IntegrationModel.php, app/Domain/Integrations/Models/IntegrationUrlModel.php, app/Domain/Integrations/Policies/IntegrationUrlPolicy.php, app/Nova/Resources/Integration.php, app/Nova/Resources/IntegrationUrl.php, app/Providers/AuthServiceProvider.php, database/migrations/2023_03_20_155932_create_integrations_urls_table.php
- Implemented a Laravel Nova resource to link URLs with a specific environment (acceptance/test/production) and a specific type (login/logout/callback) to an integration
- This PR only focuses on introducing the new Laravel Nova resource `IntegrationUrl`
- In a follow-up PR the upload to Auth0 and combined validation rules will be implemented
---
Ticket: https://jira.uitdatabank.be/browse/PPF-153
=> PPF-153 Configure auth0 client urls in Laravel Nova

app/Auth0/Auth0TenantSDK.php, app/UiTiDv1/UiTiDv1EnvironmentSDK.php, tests/Auth0/Listeners/UpdateClientsTest.php, tests/UiTiDv1/Listeners/CreateConsumersTest.php, tests/UiTiDv1/Listeners/UpdateConsumersTest.php
- Replaced Auth0 client name suffix
- Replaced UiTiD consumer name suffix
---
Ticket: https://jira.uitdatabank.be/browse/PP-168
=> PP-168 Replace Auth0 client and UiTiD consumer name suffix

README.md
- [Set php docker version to 8.2 instead of 8.1](https://github.com/cultuurnet/publiq-platform/commit/0111d12458d3cb6f0b5164899281e1ce8d6a95d6)
=> Fix docker setup in readme

app/Domain/Integrations/Controllers/IntegrationController.php, app/Router/TranslatedRoute.php, resources/translations/en.json, resources/translations/nl.json, resources/ts/Pages/Integrations/Create.tsx, routes/web.php
- [Use a language to prefix the route name](https://github.com/cultuurnet/publiq-platform/commit/9891ae8dc6344b359d5b554e0f8f9c6469effb2a)
- [Use getTranslatedRouteName for integrations redirect](https://github.com/cultuurnet/publiq-platform/commit/543285044e04b63f75b9d27bf1a7cb7d7f5f2c58)
- [Pass Accept-Language header to post request integrations](https://github.com/cultuurnet/publiq-platform/commit/6515fc02fdb0d7d4d19a1664b99a77764c4506d4)
- Fix translated route name causing duplicate route names
---
Ticket: https://jira.uitdatabank.be/browse/PPF-167
=> PPF-167 - Fix translated route name causing duplicate route names

README.md
Added a small note in the readme with a solution to get both platform and udb3-backend running at the same machine, at the same time.
=> mention solution for colliding ports with udb3-backend

app/Insightly/Listeners/UpdateOpportunity.php, app/Insightly/Listeners/UpdateProject.php, app/Insightly/Resources/InsightlyOpportunityResource.php, app/Insightly/Resources/InsightlyProjectResource.php, app/Insightly/Resources/Trait/SyncCustomFields.php, tests/Insightly/Listeners/UpdateOpportunityTest.php, tests/Insightly/Listeners/UpdateProjectTest.php, tests/Insightly/Resources/InsightlyOpportunityResourceTest.php, tests/Insightly/Resources/InsightlyProjectResourceTest.php
- Call updateSubscription when updating a project/opportunity.
- Added tests
- Filter custom fields Insightly instead of just appending 
---
Ticket: https://jira.uitdatabank.be/browse/PPF-178
=> PPF-178 Send subscription to insightly when updating project/opportunity

app/Domain/Integrations/Policies/IntegrationUrlPolicy.php
Can no longer delete login urls
I disabled deleting login urls because currently we cannot delete them because of a constraint in the SDK.
The class in the SDK cannot be extended because it is final.
A bug was logged with auth0.
I have another patch with a fix ready, but for now we will just disable the delete button.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-180
=> PPF-180 Disable deleting of login urls

database/migrations/2023_09_28_101336_add_partner_status_to_integration.php
- Add default IntegrationPartnerStatus to migration up
- displaying of integrations failing because `""` is not a valid IntegrationPartnerStatus
=> Add default IntegrationPartnerStatus to migration up

app/Domain/Integrations/Repositories/EloquentIntegrationRepository.php, tests/Domain/Integrations/Repositories/EloquentIntegrationRepositoryTest.php
- `EloquentIntegrationRepository`: added a `findOrFail()` when an `Integration` has an `update`.
- `EloquentIntegrationRepositoryTest`: make `test_it_can_update_an_integration()` more robust by adding a second integration.
- It is now possible to change the `name` (and other fields like `description`), without causing an `Integrity constraint violation`.
---
Ticket: https://jira.publiq.be/browse/PPF-246
=> PPF-246 add findOrFail() with updateQuery

app/Domain/Contacts/Models/ContactModel.php, tests/Domain/Contacts/Models/ContactModelTest.php
- `ContactModelTest`: Added Unit Tests for existing `ContactModel`
- `ContactModel`: add a check in `creating` to see if a created contributor has a softDeleted equivalent. Ifso, hardDelete it before (re)creating the `contributor`
- A previous deleted `contributor` can be recreated.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-239
=> PPF-239 Allow recreate of deleted Contributor

.github/workflows/dependabot-automerge.yml
- Enable dependabot auto-merge, see https://github.com/dependabot/fetch-metadata?tab=readme-ov-file#enabling-auto-merge
- Extra dependabot secret `DEPENDABOT_AUTO_MERGE_PERSONAL_ACCESS_TOKEN` was created, see https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic
=> Enable dependabot auto-merge

.github/CODEOWNERS
- Added `dev-publiq` as code owner so the dependabot pull requests which are auto approved by `dev-publiq` also get merged
=> Add `dev-publiq` as code owner

app/Auth0/Models/Auth0ClientModel.php, app/Domain/Integrations/Models/IntegrationModel.php, app/Nova/Actions/Auth0/DistributeAuth0Client.php, app/Nova/Actions/UiTiDv1/DistributeUiTiDv1Consumer.php, app/Nova/Resources/Auth0Client.php, app/Nova/Resources/Integration.php, app/Nova/Resources/UiTiDv1.php, app/UiTiDv1/Models/UiTiDv1ConsumerModel.php
- Added `distributed_at` column in Nova on Auth0 Client and UiTiD Consumer
- Added action to distribute Auth0 Client or UiTiD Consumer
- Show activate/block actions based on the state of the Auth0 Client or UiTiD Consumer
- Show actions on Integration correctly based on state and type
- This also fixes https://jira.publiq.be/browse/PPF-294
---
Ticket: https://jira.uitdatabank.be/browse/PPF-258
=> PPF-258 Expose distributed_at in Nova

app/Domain/Integrations/Controllers/IntegrationController.php, app/Domain/Integrations/Events/IntegrationActivationRequested.php, app/Domain/Integrations/FormRequests/ActivateWithCouponRequest.php, app/Domain/Integrations/FormRequests/CreateOrganizationRequest.php, app/Domain/Integrations/FormRequests/RequestActivationRequest.php, app/Domain/Integrations/Mappers/OrganizationMapper.php, app/Domain/Integrations/Models/IntegrationModel.php, app/Domain/Integrations/Repositories/EloquentIntegrationRepository.php, app/Domain/Integrations/Repositories/IntegrationRepository.php, app/Insightly/InsightlyServiceProvider.php, routes/web.php, tests/Domain/Integrations/Controllers/IntegrationControllerTest.php, tests/Domain/Integrations/Repositories/EloquentIntegrationRepositoryTest.php
- Added a new endpoint to request the activation of an integration. This always requires basic organization details and optional coupon and/or optional VAT details.
- The flow is exactly the same as a full activation, only the internal state of the integration is pending approval.
- Once the frontend changes are done it should be possible to remove all the deprecated code
- In the Laravel Nova admin panel an approval action needs to be added
- The link between activation and distribution of keys needs to be removed
- A combination of integration state and new field v1_allowed can replace the distributed_at field
---
Ticket: https://jira.uitdatabank.be/browse/PPF-314
=> PPF-314 activation endpoint

.env.ci, .env.example, config/nova.php, e2e/setup/auth.setup.ts, e2e/tests/integrations/create-integration-as-admin.test.ts
- [E2E admin test user credentials](https://github.com/cultuurnet/publiq-platform/commit/29c13a0d398812d09619d477dc3cc5efef93c056)
- [admin login setup](https://github.com/cultuurnet/publiq-platform/commit/a0f96c532c4788734bc4985d8adcbd07418b9062)
- [test: create integration as an admin](https://github.com/cultuurnet/publiq-platform/commit/f807d292984eaa6e951bb235f39e078c3bb65ace)
- Nova config: [Replace email with admin email](https://github.com/cultuurnet/publiq-platform/commit/e9f321590e36b0c9ee5cf57e3732774ca2276d5e)
Note: test will fail until the nova.config is deployed to acc.
You can locally test it by using the same credentials as the regular contributor
---
Ticket: https://jira.publiq.be/browse/PPF-344
=> PPF-344 - As an admin I can create an integration

app/Auth0/Listeners/CreateClients.php, app/Domain/Integrations/Events/IntegrationCreated.php, app/Insightly/Listeners/CreateOpportunity.php, app/ProjectAanvraag/Listeners/CreateWidget.php, app/ProjectAanvraag/ProjectAanvraagClient.php, app/ProjectAanvraag/ProjectAanvraagServiceProvider.php, app/ProjectAanvraag/ProjectAanvraagUrl.php, app/UiTiDv1/Listeners/CreateConsumers.php, config/project_aanvraag.php, tests/ProjectAanvraag/Listeners/CreateWidgetTest.php
Make sure time out to projectaanvraag throws exception and gets logged.
When running locally without having projectaanvraag docker running the create contact request would load endlessly
- [Add connect_timeout config option](https://github.com/cultuurnet/publiq-platform/commit/210310838c4b9f54b0adf57859ba1c85d6c0d5e8)
- [Add failed method on CreateWidget listener](https://github.com/cultuurnet/publiq-platform/commit/1b78a46e0c41d9cd6aa71c39590a616b60f4fd81)
- [Configure httpClient in provider](https://github.com/cultuurnet/publiq-platform/commit/8a2168d0a6612b9f1fa9981c7be2084c92d2ff80)
=> Add timeout to project aanvraag client

e2e/tests/integrations/create-organization-as-admin.test.ts
- [E2E test: As an admin I can create a new organization](https://github.com/cultuurnet/publiq-platform/commit/120900d9ba2c23c844c6ef63fa7236977231e552)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-347
=> PPF-347 - Add E2E test: As an admin I can create a new organization

resources/ts/Components/ActivationDialog.tsx
- Only show Price Overview in Activation Modal if not en Entry API integration
---
Ticket: https://jira.publiq.be/browse/PPF-373
=> Only show Price Overview in Activation Modal if not en Entry API integration

app/Insightly/Listeners/ActivateProject.php
- Avoid a crash by adding a missing type on the failed method of `ActivateProject`
=> Add missing type

app/Domain/Integrations/Controllers/IntegrationController.php, app/Domain/Integrations/FormRequests/KeyVisibilityUpgradeRequest.php, app/Domain/Integrations/IntegrationServiceProvider.php, app/Domain/Integrations/Listeners/UpgradeKeyVisibility.php, app/Domain/Integrations/Mappers/KeyVisibilityUpgradeMapper.php, app/Domain/Integrations/Repositories/EloquentIntegrationRepository.php, app/Domain/KeyVisibilityUpgrades/Events/KeyVisibilityUpgradeCreated.php, app/Domain/KeyVisibilityUpgrades/KeyVisibilityUpgrade.php, app/Domain/KeyVisibilityUpgrades/Models/KeyVisibilityUpgradeModel.php, app/Domain/KeyVisibilityUpgrades/Policies/KeyVisibilityUpgradePolicy.php, app/Domain/KeyVisibilityUpgrades/Repositories/EloquentKeyVisibilityUpgradeRepository.php, app/Domain/KeyVisibilityUpgrades/Repositories/KeyVisibilityUpgradeRepository.php, app/Nova/Resources/KeyVisibilityUpgrade.php, app/Providers/AppServiceProvider.php, app/Providers/AuthServiceProvider.php, database/migrations/2024_04_09_100641_create_key_visibility_upgrades_table.php, routes/web.php, tests/Domain/Integrations/Controllers/IntegrationControllerTest.php, tests/Domain/Integrations/Repositories/EloquentIntegrationRepositoryTest.php, tests/Domain/KeyVisibilityUpgrades/Repositories/EloquentKeyVisibilityUpgradeRepositoryTest.php
- Added endpoint `POST /integrations/{integrationId}/upgrade` to request the upgrade from a v1 to v2 key.
- For now, only a v1 to v2 upgrade is possible and this results in key visibility of `all` of the integrations. If needed this can be abstracted out of the HTTP request.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-376
=> PPF-376 Add endpoint to request key visibility upgrade

resources/translations/en.json, resources/translations/nl.json, resources/ts/Pages/Integrations/New.tsx
- [clarifying copy about functional and technical contacts](https://github.com/cultuurnet/publiq-platform/commit/4578b8e7c40bb6e2cb93068f99a83b5f7b04164d)
- [unnecessary margin bottom](https://github.com/cultuurnet/publiq-platform/commit/bd6dac2386597325a8c2ae311b3e30839429b631)
Screenshot:
---
Ticket: https://jira.uitdatabank.be/browse/PPF-391
=> PPF-391 - Add clarifying copy about functional and technical contacts

app/Domain/Subscriptions/SubscriptionUuid.php, database/seeders/DatabaseSeeder.php, database/seeders/SubscriptionUuid.php, database/seeders/SubscriptionsSeeder.php
- `SubscriptionsSeeder`: Added a check to see if a matching `Subscription` already exists, before adding them.
- Renamed `SubscriptionPlan` to `SubscriptionUuid`.
- Moved `SubscriptionUuid` to `seeders`-folder.
- `DatabaseSeeder`: Remove `CouponSeeder` because it should only be run locally
- Subscriptionplans are no longer overwritten with every deploy.
---
Ticket: https://jira.publiq.be/browse/PPF-429
=> PPF-429: add check to see if subscription already exists before seeding

app/ProjectAanvraag/ProjectAanvraagClient.php
- `ProjectAanvraagClient`: avoid creating a uri, with double slashes.
- No more `CORS`-errors when creating a WidgetProject.
---
Ticket: https://jira.publiq.be/browse/PPF-423
=> Avoid double slash in URI, when creating a widget.

app/Keycloak/ScopeConfig.php, config/keycloak.php, tests/IntegrationHelper.php, tests/Keycloak/ScopeConfigTest.php
Scope in Keycloak is wat determines what a client can do, in Publiq Platform this is dependant on the Integration type.
We need to know the scope id in Keycloak to add this to our client.
In a later PR an API call we be that adds this scope to a client.
Contains an extra helper for the unit tests - might seem overkill now but I will need to create a lot of integrations for later Unit tests. ;-)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-435
=> PPF-435 Added scope config for Keycloak

.env.ci, app/Console/Commands/KeycloakCreateClient.php, app/Keycloak/ClientCollection.php, app/Keycloak/KeycloakServiceProvider.php, app/Keycloak/Service/CreateClientFlow.php, app/Keycloak/Service/CreateClientHandler.php, config/app.php
This pr adds the bootstrapping / service provider of the ApiClient of Keycloak, for later use.
It also contains a class CreateClientFlow, which runs the entire flow of
- creating a client
- add the correct scope
- retrieving the client information (secret) for later storage
It also has a CLI command to create a client from an integration.
While this was not requested, it is useful as a proof of concept / handy during testing.
https://github.com/cultuurnet/appconfig/pull/616
---
Ticket: https://jira.uitdatabank.be/browse/PPF-435
=> PPF-435 Complete flow creating client keycloak

app/Keycloak/TokenStrategy/ClientCredentials.php
Fixed some unset variable notices.
PHP Warning:  Undefined array key "masterphp_client" in /var/www/html/app/Keycloak/TokenStrategy/ClientCredentials.php on line 35
PHP Warning:  Undefined array key "masterphp_client" in /var/www/html/app/Keycloak/TokenStrategy/ClientCredentials.php on line 35
PHP Warning:  Undefined array key "masterphp_client" in /var/www/html/app/Keycloak/TokenStrategy/ClientCredentials.php on line 35
=> BUGFIX Fix notice in tests

app/UiTiDv1/Jobs/ActivateConsumerHandler.php, app/UiTiDv1/Jobs/BlockConsumerHandler.php, app/UiTiDv1/Listeners/BlockConsumers.php, app/UiTiDv1/UiTiDv1ClusterSDK.php, app/UiTiDv1/UiTiDv1EnvironmentSDK.php, tests/CreateIntegration.php, tests/IntegrationHelper.php, tests/UiTiDv1/Jobs/ActivateConsumerHandlerTest.php, tests/UiTiDv1/Jobs/BlockConsumerHandlerTest.php, tests/UiTiDv1/Listeners/BlockConsumersTest.php, tests/UiTiDv1/Listeners/UpdateConsumersTest.php
Activating an integration removes the consumer groups in UiTID.
To fix this, I now always sent the groups when updating an UiTiDv1 consumer.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-488
=> PPF-488 Always send the groups when updating uitidv1

app/Keycloak/CachedKeycloakClientStatus.php, app/Keycloak/Client.php, app/Keycloak/Client/ApiClient.php, app/Keycloak/Client/KeycloakApiClient.php, app/Keycloak/Converters/IntegrationToKeycloakClientConverter.php, app/Keycloak/Listeners/CreateClients.php, app/Keycloak/Listeners/UpdateClients.php, app/Keycloak/Models/KeycloakClientModel.php, app/Keycloak/RealmCollection.php, app/Keycloak/Repositories/EloquentKeycloakClientRepository.php, app/Nova/Resources/KeycloakClient.php, database/migrations/2024_05_10_100641_create_keycloak_client_table.php, tests/Keycloak/CachedKeycloakClientStatusTest.php, tests/Keycloak/Client/KeycloakApiClientTest.php, tests/Keycloak/ClientTest.php, tests/Keycloak/Converters/IntegrationToKeycloakClientConverterTest.php, tests/Keycloak/Converters/IntegrationUrlConverterTest.php, tests/Keycloak/Jobs/BlockClientHandlerTest.php, tests/Keycloak/Jobs/UnblockClientHandlerTest.php, tests/Keycloak/Listeners/BlockClientsTest.php, tests/Keycloak/Listeners/CreateClientsTest.php, tests/Keycloak/Listeners/UpdateClientsTest.php, tests/Keycloak/Repositories/EloquentKeycloakClientRepositoryTest.php, tests/Nova/ActionGuards/Keycloak/BlockKeycloakClientGuardTest.php, tests/Nova/ActionGuards/Keycloak/UnblockKeycloakClientGuardTest.php
In preparation of the bigger work of this ticket, I added a separate client_id and integration_id for all the keycloak clients.
This will allow us to have more than 1 client per integration on a single realm.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-493
=> PPF-493 Add client id to keycloakclient

app/UiTiDv1/Listeners/UnblockConsumers.php, app/UiTiDv1/UiTiDv1ServiceProvider.php, tests/UiTiDv1/Listeners/UnblockConsumersTest.php
- `UnblockConsumers`: Add listener for `IntegrationUnblocked` for `UiTID` + Unit Test
- `UiTiDv1ServiceProvider`: Listen to `IntegrationUnblocked`
- `Consumers` are now unblocked on `UiTID`
---
Ticket: https://jira.publiq.be/browse/PPF-485
=> PPF-485 unblock on UiTID

app/Auth0/Auth0ServiceProvider.php, app/Auth0/Listeners/BlockClients.php, app/UiTiDv1/Listeners/BlockConsumers.php, app/UiTiDv1/UiTiDv1ServiceProvider.php, tests/Auth0/Listeners/BlockClientsTest.php, tests/UiTiDv1/Listeners/BlockConsumersTest.php
- Blocked Auth0 client and UiTiD consumer on integration delete
- Use `getByIdWithTrashed` inside UiTiD block handler to make sure the deleted integration can be found
- The Keycloack part is still in a separate branch
---
Ticket: https://jira.uitdatabank.be/browse/PPF-495
=> PPF-495 Block Auth0 client and UiTiD consumer on integration delete

app/Keycloak/KeycloakServiceProvider.php, app/Keycloak/Listeners/BlockClients.php, tests/Keycloak/Listeners/BlockClientsTest.php
- Deleting integration now blocks keycloak clients
BlockClients no longer fetches the integration but just uses the integration id.
- It was not needed anyway, nothing except the id is used
- It broke the delete integration flow because at that point the repository no longer finds the resource because it is deleted!
---
Ticket: https://jira.uitdatabank.be/browse/PPF-523
=> PPF-523 Deleting integration should block keycloak clients

.env.ci, app/Keycloak/Listeners/CreateClients.php, app/Keycloak/Listeners/UpdateClients.php, app/Keycloak/Realms.php, app/Keycloak/ScopeConfig.php, tests/Keycloak/RealmFactory.php, tests/Keycloak/RealmsTest.php, tests/Keycloak/ScopeConfigTest.php
- Made it possible for specific types of clients to have multiple scopes assigned to it.
- Entry API -> has now -> Entry api scope + sapi3 scope
- Uitpas scope -> has now -> Entry api scope + sapi3 scope + uitpas scope
- Widgets do not have its own scope, so I removed this and replaced it with SAPI3 scope.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-520
=> PPF-520 Bugfix - Missing client scope for Entry API integrations

app/Keycloak/Client/KeycloakApiClient.php, app/Keycloak/Converters/IntegrationToKeycloakClientConverter.php, app/Keycloak/Converters/IntegrationUrlConverter.php, app/Keycloak/Listeners/UpdateClients.php, tests/Keycloak/Converters/IntegrationToKeycloakClientConverterTest.php, tests/Keycloak/Converters/IntegrationUrlConverterTest.php, tests/Keycloak/Listeners/UpdateClientsTest.php
We need to sent a slight different payload to Keycloak to create a client, based on feedback from Erwin and Corneel.
- Add https://docs.publiq.be/ / https://publiq.stoplight.io/ to allow web origins (CORS)
- Add hidden attribute "origin" to "publiq-platform" -> this will be used later to clear test clients (discussed with Erwin)
- Set  'use.refresh.tokens' => true (discussed with Erwin)
- Added extra test to see that the IntegrationToKeycloakClientConverter & IntegrationUrlConverter play well together
- BUGFIX Switch Login and Callback URL, you can only have 1 login url but multiple callback urls
---
Ticket: https://jira.uitdatabank.be/browse/PPF-525
=> PPF-525 Changed payload create client Keycloak

app/Domain/Auth/Controllers/LogoutController.php, app/Nova/Resources/KeycloakClient.php
- Changed "open in keycloak" link to new format (thank you Erwin)
- Logout url was broken because auth::logout() deletes the id token but I need to sent this to Keycloak.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-450
=> PPF-450 Minor changes - Fix logout / fix open in keycloak link

app/Domain/Integrations/FormRequests/StoreIntegrationRequest.php, app/Domain/Integrations/FormRequests/UpdateIntegrationRequest.php, lang/nl/validation.php, resources/translations/en.json, resources/translations/nl.json, resources/ts/Pages/Integrations/New.tsx
- UiTPAS agreement checkbox
---
Ticket: https://jira.uitdatabank.be/browse/PPF-516
=> PPF-516-UiTPAS checkbox

resources/translations/en.json, resources/translations/nl.json
* Punctuation marks
---
Ticket: https://jira.uitdatabank.be/browse/PPF-542
=> Add punctuation marks

app/Providers/NovaServiceProvider.php
- Make Integrations index the default Nova admin page
---
Ticket: https://jira.publiq.be/browse/PPF-524
=> Make Integrations index the default Nova admin page

app/Auth0/Auth0ServiceProvider.php
- `Auth0ServiceProvider`: Check if either `Keycloak` or `auth0` is enabled to create Clients.
- Environments who are still on `auth0` can again create Clients.
---
Ticket: https://jira.publiq.be/browse/PPF-547
=> HOTFIX: Check if both auth0 & keycloak are enabled.

app/Auth0/Auth0ServiceProvider.php
I Removed the keycloak flag for auth0 creation check, it has nothing to do with this.
The check for Keycloak clients is in it's own KeycloakServiceProvider
=> Remove keycloak flag for auth0 creation check

app/Domain/Integrations/Models/IntegrationModel.php
The UiTdatabank organizers linked to an UiTPAS integration do not load in the admin panel. (409 error).
The problem is that on this API call the $resource is not loaded in the IntegrationModel (aka the fields).
This means that the method isUitpas() always returns false, because the $type is not set.
As a (quick) fix I set the default value of type to Uitpas.
On the UI overview pages the Integration is loaded in, so this overwrites the default value.
Know problem: When creating an integration in the Admin UI the Type is as a default Uitpas
Known Limitation: If we ever have 2 different values in type that toggle conditions, we have a problem.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-553
=> PPF-553 BUGFIX Organizers gives 409 in admin panel

app/Domain/Integrations/Repositories/EloquentIntegrationRepository.php, tests/Domain/Integrations/Repositories/EloquentIntegrationRepositoryTest.php
For UiTPAS API integration, the key visiblity must always be v2
As discussed with Corneel, this is only changed for Integrations created in the frontend.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-555
=> PPF-555 For uitpas integration always use key visibility v2

app/Nova/Actions/ActivateUitpasIntegration.php, app/Nova/Resources/Integration.php
- `ActivateUitpasIntegration`: Action to activate an UiTPAS-integration with 1 or more Organizers.
- `Resources/Integration`: Injected `ActivateUitpasIntegration` into Integration
- An admin can now activate an Integration with 1 or More ID's of an `Organizer`
---
Ticket: https://jira.publiq.be/browse/PPF-459
=> PPF-459 uitpas integration activation

resources/ts/Components/Integrations/Detail/IntegrationSettings.tsx, resources/ts/types/Integration.ts
- Only display URL settings for First party partners
---
Ticket: https://jira.publiq.be/browse/PPF-530
=> Only display URL settings for First party partners

app/Domain/Integrations/Controllers/IntegrationController.php, app/Domain/Integrations/Mappers/UdbOrganizerMapper.php, app/Domain/Integrations/Repositories/EloquentIntegrationRepository.php, app/Domain/Integrations/Repositories/EloquentUdbOrganizerRepository.php, app/Domain/Integrations/Repositories/IntegrationRepository.php, app/Domain/Integrations/Repositories/UdbOrganizerRepository.php, app/Domain/Integrations/UdbOrganizerCollection.php, app/Domain/Integrations/UdbOrganizers.php, app/Nova/Actions/ActivateUitpasIntegration.php, app/Nova/Resources/Integration.php, tests/Domain/Integrations/Repositories/EloquentIntegrationRepositoryTest.php, tests/Domain/Integrations/Repositories/EloquentUdbOrganizerRepositoryTest.php
- Added new unit tests for UdbOrganizerRepository, class was untested.
- Added new check in EloquentIntegrationRepositoryTest to make sure Organizers are created in db.
- Added new Collection for UdbOrganizer
- 
- Added 2 versions of UdbOrganizerRepository::create(), the new one is called "createInBulk", the later one wraps all inserts in a transaction.
- requestActivation and activateWithOrganization now wrap the creation of the Organizer.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-562
=> PPF-562 Create helper method to activate uitpas integration with organizers

resources/ts/i18n/initializeI18n.ts
- Fixed locale detection not ignoring non-locale path fragments
---
The URL detector in `i18next-browser-languagedetector` actually uses any first path fragment present when trying to find the language, so going to `/admin/somefakeurl` will try to set `admin` as locale, which hits the Widget validation logic as it should
Ticket: https://jira.publiq.be/browse/PPF-568
=> Ensure locale detection ignores non-locale path fragments

resources/ts/Components/Navigation.tsx, routes/web.php
- [Make support route not protected](https://github.com/cultuurnet/publiq-platform/commit/664a8452cfb1882fa133e726e95dcfe98cefde70)
- [Show less pages when authenticated](https://github.com/cultuurnet/publiq-platform/commit/2fbf14d91b7c9fb69e3b3b69bd9f8d23af689d0e)
---
Ticket: https://jira.uitdatabank.be/browse/PPF-584
=> PPF-584 - Fix remarks top navigation

tests/Domain/Integrations/Repositories/EloquentIntegrationRepositoryTest.php, tests/Domain/KeyVisibilityUpgrades/Repositories/EloquentKeyVisibilityUpgradeRepositoryTest.php, tests/Domain/Mail/MailManagerTest.php, tests/Keycloak/Client/KeycloakApiClientTest.php, tests/Keycloak/Converters/IntegrationToKeycloakClientConverterTest.php, tests/Keycloak/Listeners/BlockClientsTest.php, tests/Keycloak/ScopeConfigTest.php
- `tests/*`: Replaced all `dataProviders` in `DocBlocks`
- `test/*`: Replace 1 occurence of `@test` in `DocBlock`
- No more deprecation Warnings, when running the Unit tests.
---
Ticket: https://jira.publiq.be/browse/PPF-610
=> PPF-610 PHPUnit deprecation fixes

config/keycloak.php
- Removed all references to KEYCLOAK_ACC_SCOPE_WIDGETS_ID, because this is not used anywhere.
Background: widgets scope is just the combined scope of sapi3 + entry api.
=> Remove unused config value

app/Nova/Resources/UiTiDv1.php
- `Nova/Resources/UiTiDv1`: Do not show `consumerKey` & `consumerSecret`
- `UiTIDv1` `consumerKey` & `consumerSecret` are hidden in the Nova Admin panel.
---
Ticket: https://jira.publiq.be/browse/PPF-608
=> PPF-608 hide UiTIDv1 consumer_key & consumer_secret in Nova

app/Keycloak/TokenStrategy/ClientCredentials.php
On test / prod Keycloak is broken because the cache for the token caches based on the realm name. But both test/acc/prod have a realm called "master", so it only cached the first, which was the acc env.
This fixes this by adding the url to the cache key.
=> HOTFIX - cache is too agressive and caches only the ACC master realm key

app/Console/Commands/Migrations/MigrateAuth0ToKeycloakClients.php, app/Keycloak/Repositories/KeycloakClientRepository.php
When the production realm of Keycloak is not configured, as is the case on the Test server, the migration script of auth0 -> keycloak would fail the very first time it would try to create a "prod" client.
I now catch this exception and just log it, it is oke that the test env does not have production clients.
=> BUGFIX When prod realm is missing migration script fails

app/Domain/Integrations/Events/IntegrationApproved.php, app/Domain/Integrations/Models/IntegrationModel.php, app/Domain/Mail/MailManager.php, app/Mails/MailServiceProvider.php, tests/Domain/Integrations/Models/IntegrationModelTest.php, tests/Domain/Mail/MailManagerTest.php
Previously we only sent a mail when an integration is activated, however entry-api goes trough an approval flow so it never gets "activated", it gets "approved".
The same mail is sent however in both cases.
I needed to add a new event to cover this use case.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-56
=> PPF-56 Send mail when integration is approved

config/mailjet.php
I used the wrong env value for the final reminder email.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-605
=> PPF-605 Used wrong config value for final reminder email

app/Auth0/Auth0ServiceProvider.php
- Avoid binding `Auth0ManagementUserRepository` to `UserRepository`
---
Ticket: https://jira.uitdatabank.be/browse/PPF-625
=> PPF-625 Avoid binding `Auth0ManagementUserRepository` to `UserRepository`

app/Http/Middleware/HandleInertiaRequests.php, resources/ts/Components/IntegrationClientCredential.tsx, resources/ts/types/PageProps.ts
- Fixed blank UI for integrations with no keycloak client
---
@simon-debruijn @grubolsch Some integrations do not yet have a Keycloak client to show, even if the related env variables are enabled. As it is my understanding that this is an "unhappy path" state, and that otherwise we should always have one to show, I've tried to simplify the logic to trust the data first and foremost in the meantime, so that users aren't too confused. But since the previous condition relied on `KEYCLOAK_TEST_CLIENT_ENABLED` – which from my understanding is a temporary thing – I'm a bit unsure what the actual real condition should be if that's not enough. Especially the isLive part. So all that to say I tried to trust the data in place but perhaps it's shortsighted.
---
Ticket: …
=> Fixed blank UI for integrations with no keycloak client

app/Domain/Integrations/Controllers/IntegrationController.php, app/Domain/Integrations/Integration.php, resources/ts/Components/IntegrationCard.tsx, resources/ts/Components/IntegrationClientCredential.tsx, resources/ts/Components/Integrations/Detail/Credentials.tsx, resources/ts/Components/Integrations/Detail/CredentialsAuthClients.tsx, resources/ts/Pages/Integrations/Index.tsx, resources/ts/Pages/Integrations/New.tsx, resources/ts/types/Auth0Tenant.ts, resources/ts/types/Credentials.ts, resources/ts/types/Integration.ts, resources/ts/types/PageProps.ts
- Remove auth0 specific code
---
Ticket: https://jira.uitdatabank.be/browse/III-6402
=> III-6402 - Remove auth0 specific code

resources/ts/Components/UitIdWidget.tsx
- revert `oAuthDomain` back to `auth0Domain`, because external library still uses it.
- The top `UiTID Widget` bar is show again
---
=> Hotfix UiTID Widget

tests/Domain/Integrations/Repositories/EloquentIntegrationRepositoryTest.php
- `EloquentIntegrationRepositoryTest`: Refactored `test_get_drafts_by_type_and_between_months_old()` to compare `Collection` instead of a `dataProvider`
---
Ticket: https://jira.publiq.be/browse/PPF-652
=> PPF-652 improve test_get_drafts_by_type_and_between_months_old()

app/Domain/Auth/Models/UserModel.php, tests/Domain/Auth/Models/UserModelTest.php
- Fallback to an empty string when `name` is missing instead of crashing, as long as `email` is present all functionality works.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-654
=> PPF-654 Fallback for missing name

app/Providers/NovaServiceProvider.php
- Register Nova routes after upgrade to Laravel Nova 5
=> Hotfix to register Laravel Nova routes

app/Keycloak/Jobs/BlockClientHandler.php, app/Keycloak/Jobs/UnblockClientHandler.php, app/Keycloak/Listeners/CreateClients.php, app/UiTiDv1/Jobs/BlockConsumerHandler.php, app/UiTiDv1/Jobs/UnblockConsumerHandler.php
- Don't just log but also capture Keycloak exceptions during client creation
---
We seem to be throwing the Exception with the entire response from the API, so I don't think there is that much additional information to log that could help with the error in the screenshot since it seems Keycloak really is just returning "401 Unauthorized" without elaboration. 
So this change should at least prevent Keycloak exceptions from not reaching Sentry, as currently they are caught and logged but not released back for capture by Sentry? This will hopefully provide us with a lot more metadata to understand what goes wrong.
Ticket: https://jira.publiq.be/browse/PPF-659
=> Don't just log but also capture Keycloak exceptions during client creation

app/Domain/Auth/Controllers/CallbackController.php, app/Keycloak/KeycloakConfig.php, app/Providers/AuthServiceProvider.php, config/keycloak.php, tests/Domain/Auth/Controllers/CallbackControllerTest.php
- This PR introduces 2FA for admin users (defined in nova_users.php config).
It leverages elevated authentication to enforce this behavior.
- This feature is protected by a feature flag (KEYCLOAK_ENFORCE_2FA_FOR_ADMINS) to allow a staggered rollout to acc/test/prod.
All users authenticate normally via Keycloak.
On callback, we check the ACR level (acr) returned by Keycloak.
If the user is in nova_users.php but doesn't have the highest ACR, we trigger a re-login with acr_values=highest to enforce 2FA (OTP).
Once authenticated at the required level, the user is logged in as usual.
https://github.com/cultuurnet/appconfig/pull/1005
---
Ticket: https://jira.uitdatabank.be/browse/PPF-655
=> PPF-655 Add 2FA for admins

app/Providers/NovaServiceProvider.php
- `NovaServiceProvider`: override `authorization()` to not allow everybody on localhost.
- The `local`-environment mimicks more closely the `server`-environments
---
=> Do not allow everybody on admin panel on dev

resources/ts/Components/Integrations/Detail/OrganizersDatalist.tsx
- Got the error "OrganizersDatalist.tsx:122 Invalid prop id supplied to React.Fragment. React.Fragment can only have key and children props." in the console.
If I understand correctly, I am getting this error because the code uses a "Fragment" a component FormElement, and that component is trying to pass extra props like id internally. However, a fragment can only have key and children as props, which is why it fails. Do I understand correctly?
But I might miss nuance in this approach, so please verify.
=> [minor] fix invalid prop id error

app/Domain/Integrations/Repositories/EloquentUdbOrganizerRepository.php, app/Mails/MailServiceProvider.php, app/Nova/Actions/UdbOrganizer/RequestUdbOrganizer.php, app/Nova/Actions/UdbOrganizer/RevokeUdbOrganizer.php, app/Nova/Resources/Integration.php, app/Nova/Resources/UdbOrganizer.php, app/UiTPAS/UiTPASApi.php, app/UiTPAS/UiTPASApiInterface.php, tests/Domain/Integrations/Repositories/EloquentUdbOrganizerRepositoryTest.php, tests/Nova/Actions/UdbOrganizer/RequestUdbOrganizerTest.php, tests/Nova/Actions/UdbOrganizer/RevokeUdbOrganizerTest.php, tests/UiTPAS/UitpasApiTest.php
- Added new option to an approved organizer: "revoke permissions". This will remove the organizer from the db and revoke his permissions in UiTPAS.
- Admin added organisations are directly approved, and only recieve the final "approved" email.
- Made status field for organizer visually the same as other status fields in PPF. (color = green)
- UpdateStatus() organizer method was bugged, updated all data, without a where-statement.
---
Ticket: https://jira.uitdatabank.be/browse/PPF-693
=> PPF-693 Cleanup permissions when revoking organizer

resources/translations/en.json, resources/translations/nl.json, resources/ts/Components/IntegrationCard.tsx, resources/ts/Components/Integrations/Detail/CredentialsAuthClients.tsx, resources/ts/Components/Integrations/Detail/OrganizersInfo.tsx, resources/ts/Pages/Integrations/Detail.tsx
Several visual improvements for the organizers tab.
- Added new button "Vraag extra rechten voor organisaties" on the integration overview page for live integrations
- Added new button "Vraag extra rechten voor organisaties" on the integration detail page for live integrations
- Add new text below "test omgeving" to point to the right "get started" guide.
- Less space between headers and text (gap distance) on organizer page.
- Change first header size to make it bigger than the other titles (h4 -> h3)
- Changed text for header "live" -> "Productie omgeving"
- Changed text for header "test -> "Test omgeving"
- Moved "organizer" tab to second slot (only visible for UiTPAS) because the tab is really important.
- Make permissions show up in 2 columns
- Documentation link to get started with …
=> PPF-686 [Frontend] Visual improvements for the organizers tab.
